### PR TITLE
Update index state

### PR DESCRIPTION
**Pull request by mrBliss**

### CODE REVIEW

**Comment by mrBliss** [comment]
@newhoggy This includes #1928 until that is merged.

**Comment by mrBliss** [comment]
Uggh, Nix can't solve the dependencies while Cabal (w/o Nix) can solve it just fine on my machine.

**Comment by mrBliss** [comment]
CI was green (https://hydra.iohk.io/eval/968356). I rebased against master and squashed a commit. Ready to merge.

**Review by Jimbo4350 — APPROVED** [review]

**Comment by mrBliss** [comment]
bors merge

**Pull request merged**
