### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dcoutts**
And a few required code changes.

We could add more newly-available detail in the tracers. This is a
minimal update.

### CODE REVIEW

**Comment by dcoutts** [comment]
This depends on https://github.com/input-output-hk/ouroboros-network/pull/2645

**Comment by mrBliss** [comment]
> This depends on [input-output-hk/ouroboros-network#2645](https://github.com/input-output-hk/ouroboros-network/pull/2645)

Merged.

**Review by mrBliss — APPROVED** [review]
Consensus changes (mostly ledger-related, though) look good.

This won't include https://github.com/input-output-hk/cardano-ledger-specs/pull/1881. Let me know if you want that in this release, it will require bumping consensus (still needs to update ledger-specs to include 1881) and ledger-specs.

**Review by newhoggy — APPROVED** [review]

**Review by erikd — APPROVED** [review]

**Comment by dcoutts** [comment]
bors merge

**Pull request merged**
