### PR TITLE
Bump to latest cardano-ledger-specs.

### PR DESCRIPTION
**Pull request by nc6**
Since the ledger is now starting to generalise things for Alonzo, some
similar changes must be made here:

- Reference to the `EraRule` family, which is used to encode the set of
  rules used in a given era.
- Various things (particularly `TxOut`) are now era-dependent, and so we
  cannot assume a Shelley-era TxOut.

### CODE REVIEW

**Comment by nc6** [comment]
I'm rebasing this atop master atm

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by dcoutts** [comment]
bors merge

**Review by newhoggy — APPROVED** [review]

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
