### PR TITLE
Adjust chairman logging configuration

### PR DESCRIPTION
**Pull request by newhoggy**
Adjust chairman logging configuration as per the following:

```
TraceIpSubscription at Info level
TraceMux at Info level (Debug would be too noisy)
DnsSubscription can be turned off as the test is not using dns addresses
Handshake cat be used at Debug level
```

### CODE REVIEW

**Review by Jimbo4350 — APPROVED** [review]

**Review by coot — APPROVED** [review]
LGTM and thanks!

**Comment by coot** [comment]
This is useful in #1928

bors merge

**Review by dcoutts — APPROVED** [review]

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
There's a commit on `master` which removes the port check that's been failing and replaces it with a more robust socket file check.  It's worth rebasing to avoid the **Haskell CI / build (8.6.5, windows-latest)** failure.

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
