### PR TITLE
WIP New tracing infrastructure

### PR DESCRIPTION
**Pull request by deepfire**
This is the new tracing infrastructure, that is intended as replacement for `iohk-monitoring-framework` and the related integration code in `cardano-node`.

The documentation is at https://github.com/input-output-hk/cardano-node/tree/tracing-master/trace-dispatcher/docs/trace-dispatcher.md

# TODO

## Library trace-dispatcher

- [X] Add frequency limiting
  - [X] Testen

- [x] Add continued message to frequency limiting
  - [x] Testen

- [X] Add queue size trace forwarder to config
  - [X] Testen

- [X] Add color arg to backend config?
  - [x] Testen

- [X] Formatting optimization
  - [X] Testen
  
- [x] Add check code for configuration and wiring

- [x] Framework functionality tests !!!
  - [X] Privacy
  - [ ] DetailLevel
  - [x] Backend routing
  - [ ] Backend formatting
  - [x] Severity filtering
  - [ ] Freuqency limiting

- [X] Comment library code  

- [X] Document configuration
        nix/workbench/profiles/node-services.nix
        scripts/lite/configuration/shelley-*.yaml  
          ./scripts/lite/shelley-testnet.sh

## Integration

- [x] Ensure completeness of set of Metrics
  - [x] Add aggregation cases

- [x] Ressource stat tracers 
  - [X] Linux 
  - [x] Windows and Mac testing

- [X] Basic info tracers

- [X] Rebase on latest master

- [x] Fix privacy for all tracers!
- [ ] Fix namespaces for all tracers

- [ ]  External changes:
  - [ ] Reconfigure call.
  - [X] Reconfigure and forwarder? (Dont do)
  - [ ] Document call (with fileName).
  - [x] No strictness annotations for: Mempool

- [x]  Solution for: cardano-tracer does not see start of traces, because always connect after start of node
  - [x] One possible solution: Have big queue in the node at startup
  - [x] Implement
  - [x] Test

## Next steps

- [ ] Benchmark trace-dispatcher in comparison to old tracers

- [ ] Test forwarder cache performance
- [ ] Test forwarder cache overflow

- [ ] Second phase
  - [ ] Remove old tracers

### CODE REVIEW

**Comment by denisshevchenko** [comment]
The first PR for the new tracing infrastructure is open: https://github.com/input-output-hk/cardano-node/pull/2960

**Comment by denisshevchenko** [comment]
Our second PR is open: https://github.com/input-output-hk/cardano-node/pull/3073

**Comment by denisshevchenko** [comment]
The next PR: https://github.com/input-output-hk/cardano-node/pull/3337

**Comment by denisshevchenko** [comment]
The next PR: https://github.com/input-output-hk/cardano-node/pull/3342

**Comment by denisshevchenko** [comment]
The next PR, integration in the node: https://github.com/input-output-hk/cardano-node/pull/3450

**Comment by denisshevchenko** [comment]
The next PR: https://github.com/input-output-hk/cardano-node/pull/3496

**Comment by denisshevchenko** [comment]
The next PR: https://github.com/input-output-hk/cardano-node/pull/3498

**Comment by deepfire** [comment]
The tracing system integration PR was merged, so this no longer has purpose of serving as integration.

**Pull request closed without merging**
