### PR TITLE
tx generator docs

### PR DESCRIPTION
**Pull request by MarcFontaine**
Add some documentation to the transaction generator

### CODE REVIEW

**Review by deepfire — APPROVED** [review]
Thank you Marc!

**Comment by MarcFontaine** [comment]
TODO: Quite some of the documentation already needs updates

**Comment by MarcFontaine** [comment]
@deepfire @mgmeier I'm closing this PR.
This documentation was meant as an overview and starting point on the tx-generator.
It reflects the state of the project as of February 2020 and is mostly outdated by now.
@mgmeier has taken over the main development of the tx-generator.
Please feel free to reopen if you want to carry on with this PR.

**Pull request closed without merging**
