### PR TITLE
Byron only testnet and chairman test

### PR DESCRIPTION
**Pull request by newhoggy**
We already had the code for this, but it wasn't set up to actually run the chairman test or exposed to the CLI to run a testnet.  This change exposes that functionality.

### CODE REVIEW

**Review by erikd — APPROVED** [review]

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
bors merge

**Comment by craigem** [comment]
bors try

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
