### PR TITLE
nix: Fix a component option typo

### PR DESCRIPTION
**Pull request by rvl**
- Fix a nix evaluation error
- Make the `result` symlinks only be ignored at the repo top-level.

### CODE REVIEW

**Review by jbgi — APPROVED** [review]

**Comment by rvl** [comment]
Thanks @jbgi

bors r+

**Review by hamishmack — APPROVED** [review]

**Comment by nc6** [comment]
bors merge

**Comment by rvl** [comment]
bors merge

**Comment by rvl** [comment]
Appears to be fixed now in `master`.

**Pull request closed without merging**
