### PR TITLE
Unbreak build with Cardano.Logging.Resources.Dummy module.

### PR DESCRIPTION
**Pull request by arrowd**
While there, fix the typo in the function name.

### CODE REVIEW

**Review by cblp — APPROVED** [review]

**Comment by reqlez** [comment]
Looking forward! I ran into an issue compiling on FreeBSD looks like this could be the fix.

**Review by denisshevchenko — APPROVED** [review]

**Comment by arrowd** [comment]
What's blocking this now?

**Comment by arrowd** [comment]
Bump.

**Comment by reqlez** [comment]
Bump Bump ;-)

**Comment by arrowd** [comment]
Bump.

**Comment by arrowd** [comment]
Can this PR be finally merged in?

**Comment by reqlez** [comment]
@JaredCorduan any chance this can make it into 1.35.0 release to fix building cardano-node on FreeBSD ? It has been broken since 1.34.0 :(  We are literally using patches right now to build:

https://github.com/freebsd/freebsd-ports-haskell/blob/cardano/net-p2p/cardano-node/files/patch-trace-resources_src_Cardano_Logging_Resources_Dummy.hs

https://github.com/freebsd/freebsd-ports-haskell/blob/cardano/net-p2p/cardano-node/files/patch-trace-resources_trace-resources.cabal

It has 2 approvals already.

**Comment by JaredCorduan** [comment]
sorry for the wait @arrowd @reqlez , and thank you for the PR! :raised_hands:

**Pull request merged**
