### PR TITLE
Fix gen-cabal-nosystemd.sh

### PR DESCRIPTION
**Pull request by hasufell**
related https://github.com/input-output-hk/cardano-node/issues/2001 @mark-stopka

### CODE REVIEW

**Comment by mark-stopka** [comment]
@hasufell I am sending you much love from Czech Republic and reporting back that this patch fixes the issue for current master...

**Review by intricate — APPROVED** [review]

**Review by dcoutts — APPROVED** [review]

**Comment by dcoutts** [comment]
bors merge

**Comment by mark-stopka** [comment]
I also confirm that `git cherry-pick -m 1 -n 66897326c457bd665651c28388ef2c1ec3af83f7` fixes the issue for 1.24.2...

**Pull request merged**
