### PR TITLE
Relax Byron chairman assertion from 53 to 52

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by newhoggy** [comment]
This is to address this intermittent failure:

https://github.com/input-output-hk/cardano-node/runs/1512570166?check_suite_focus=true

```
              85 ┃         H.cat nodeStderrFile
                 ┃         │ Reading file: /Users/runner/work/_temp/chairman/test-6aea771c1b4a2bad//logs/chairman.stderr.log
                 ┃         │ ━━━━ File: /Users/runner/work/_temp/chairman/test-6aea771c1b4a2bad//logs/chairman.stderr.log ━━━━
                 ┃         │ cardano-node-chairman: ProgressFailure (BlockNo 53) "test-6aea771c1b4a2bad/socket/node-0" (Tip (SlotNo 60) afeb9bd944c208e29135cb39ca7ba54a48a6fafa993179ab493ba6277e421980 (BlockNo 52))
                 ┃         │ 
              86 ┃         H.failure
                 ┃         ^^^^^^^^^
```

**Review by deepfire — APPROVED** [review]
LGTM!

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
bors merge

**Review by erikd — APPROVED** [review]

**Comment by newhoggy** [comment]
Thanks!

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
