### PR TITLE
update cardano-prelude deps

### PR DESCRIPTION
**Pull request by karknu**

### CODE REVIEW

**Comment by denisshevchenko** [comment]
`stack build` returns this error:

```
/var/lib/buildkite-agent/.stack/snapshots/x86_64-linux-nix/custom-cardano-snapshot-Et3twIuwwZqa/8.6.5/bin/happy: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

**Comment by deepfire** [comment]
The community voted to override BORS.

**Pull request merged**
