### PR TITLE
[#303] more information on replay events

### PR DESCRIPTION
**Pull request by CodiePP**
on startup the node can take some time to replay intermittent block data.
this PR adds more logging that should show these events in the log.

### CODE REVIEW

**Comment by CodiePP** [comment]
depends on https://github.com/input-output-hk/iohk-monitoring-framework/issues/459

**Comment by CodiePP** [comment]
> Tracing every `LedgerDB.ReplayedBlock` is way too verbose. Potentially thousands of such messages would be traced.

we can now elide messages (see #303)

**Comment by mrBliss** [comment]
> with Serge's latest tracer transformer we can now suppress the logging of repetitive ReplayEvent messages:
> 
> ```
> [nixos19:cardano.node:Info:4] [2019-12-13 17:15:21.31 UTC] {"event":{"snapshot":{"kind":"snapshot"},"kind":"TraceLedgerReplayEvent.ReplayFromSnapshot","tip":"Tip (At (Block {blockPointSlot = SlotNo {unSlotNo = 25811}, blockPointHash = ByronHash {unByronHash = AbstractHash 381d72cc70ea65e242e27d2555010067c02fa5dec92c64f76e4f92102e3edae7}}))"},"kind":"TraceEvent","tip":"genesis(origin)"}
> [nixos19:cardano.node.synopsis:Info:4] [2019-12-13 17:15:21.32 UTC] Similar messages elided, 10 total.
> [nixos19:cardano.node:Info:4] [2019-12-13 17:15:21.32 UTC] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"21600","epoch":"1"},"kind":"TraceEvent","tip":"genesis(origin)"}
> ```
What exactly is "repetitive"? I'm assuming multiple messages with the same _constructor_, not multiple messages that are equal `Eq`), right?

So if we're replaying 500 blocks, will the output be something like the following?
```
[..] {"event":{"snapshot":{"kind":"snapshot"},"kind":"TraceLedgerReplayEvent.ReplayFromSnapshot","tip":"Tip (At (Block {blockPointSlot = SlotNo {unSlotNo = 25811}, blockPointHash = ByronHash {unByronHash = AbstractHash 381d72cc70ea65e242e27d2555010067c02fa5dec92c64f76e4f92102e3edae7}}))"},"kind":"TraceEvent","tip":"genesis(origin)"}
[..] Similar messages elided, 100 total.
[..] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"..","epoch":".."},"kind":"TraceEvent","tip":"genesis(origin)"}
[..] Similar messages elided, 100 total.
[..] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"..","epoch":".."},"kind":"TraceEvent","tip":"genesis(origin)"}
[..] Similar messages elided, 100 total.
[..] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"..","epoch":".."},"kind":"TraceEvent","tip":"genesis(origin)"}
[..] Similar messages elided, 100 total.
[..] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"..","epoch":".."},"kind":"TraceEvent","tip":"genesis(origin)"}
[..] Similar messages elided, 100 total.
[..] {"event":{"kind":"TraceLedgerReplayEvent.ReplayedBlock","slot":"..","epoch":".."},"kind":"TraceEvent","tip":"genesis(origin)"}
```

**Comment by deepfire** [comment]
> What exactly is "repetitive"? I'm assuming multiple messages with the same constructor, not multiple messages that are equal Eq), right?

@mrBliss, it's fully general (from https://github.com/input-output-hk/iohk-monitoring-framework/blob/master/tracer-transformers/src/Control/Tracer/Transformers/Synopsizer.lhs#L52):

> -- The transformer is specified in terms of an internal counter (starting at zero),
> --   and a given predicate on the state of the counter and the pair of subsequent messages.
> --   If the predicate returns 'False', the message is suppressed, and the counter is increased.
> --   Otherwise, the counter is reset to zero, and:
> --     - the message is wrapped into 'One',
> --     - an additional 'Many' message is added for the predecessor, if the counter was zero.

**Comment by CodiePP** [comment]
replaced with PR #445

**Pull request closed without merging**
