### PR TITLE
Updated readme and deleted placeholder test folder

### PR DESCRIPTION
**Pull request by oneEdoubleD**
Deleted a placeholder folder/file for tests. Updated readme to explain current test coverage.

### CODE REVIEW

**Comment by erikd** [comment]
This section of the cabal file should also go https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/cardano-node.cabal#L152-L170

**Comment by oneEdoubleD** [comment]
Done

**Comment by dcoutts** [comment]
bors merge

**Comment by dcoutts** [comment]
gah, that's what I get for not reloading the page first

**Pull request merged**
