### PR TITLE
Update the getting started documentation.

### PR DESCRIPTION
**Pull request by nc6**
- Remove the duplicate pages on building and installing.
- Add a small preamble
- Add a TODO section on using pre-built binaries
- Fix the nix build instructions
- Consolidate instructions on building without nix.

### CODE REVIEW

**Comment by nc6** [comment]
Need some assistance on finding the pre-built binaries.

**Comment by newhoggy** [comment]
Please rebase.

**Review by olgahryniuk — APPROVED** [review]

**Comment by robcohen** [comment]
@brunjlar @kevinhammond can you please review and comment?

**Review by nahern — APPROVED** [review]
approved changes.

**Pull request closed without merging**
