### PR TITLE
Bump ouroboros-network (fix memory leak).

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by mrBliss** [comment]
Note that there's still a slow memory leak in the node, but after investigating it the past few days, I'm getting more and more confident that it is not in consensus (`ouroboros-network`) but in `cardano-node`.

**Comment by jbgi** [comment]
bors retry

**Comment by jbgi** [comment]
bors retry

**Comment by jbgi** [comment]
bors retry

**Pull request merged**
