### PR TITLE
View transactions for Alonzo era

### PR DESCRIPTION
**Pull request by Titan-C**
It is very frustrating no to be able to inspect the transactions. Issue #3039 

This is my take, and it gets me far enough to solve my problem and review the transaction I just built.

For example transaction 2fff0843927b1bb3ec4accb528953e3205ab95544610951e3c882810d6a19763 in Alonzo Purple looks like:
```bash
cardano-cli view --tx-file tx.signed
```
```
auxiliary data: null
auxiliary data hash: null
certificates: []
collateral:
- 0ff7d2b64dc862ae7971fcc34613532911bc2c228fe5600fa99368204e20e007#1
era: Alonzo
fee: 205683
inputs:
- 821f47e158632a0b28627d437c0ad5dd5bb4b99db0c312a836a6c454b2ae8a52#2
- de7468db3d8b49592a408fbea0229333839cf570cd824f6c08c6923a30fc2260#1
mint:
  lovelace: 0
  policies: {}
outputs:
- address:
    Bech32: addr_test1qrv07g3hcxud3u07xh2jshp0xdvwhv83x4783cg0d9k7qj0d39qa5wq62697ezhn0tek2gxv2kglgz7umgahh6vlf2lqm8dfzp
    credential:
      key hash: d8ff2237c1b8d8f1fe35d5285c2f3358ebb0f1357c78e10f696de049
    network: Testnet
    stake reference: StakeRefBase (KeyHashObj (KeyHash "ed8941da381a568bec8af37af36520cc5591f40bdcda3b7be99f4abe"))
  amount:
    lovelace: 26794317
    policies: {}
  datumhash: null
req signer hashes: []
script data: TxBodyScriptData ScriptDataInAlonzoEra TxDatsRaw (fromList [(SafeHash
  "24e35c5e39e4a20735f10cd41b63d268a8c959bd15229ec925f8b0365ed8932b",DataConstr B
  "Satoshi Nakamoto")]) RedeemersRaw (fromList [(RdmrPtr Spend 0,(DataConstr B "Ends",ExUnits
  {exUnitsMem = 160, exUnitsSteps = 1624000})),(RdmrPtr Spend 1,(DataConstr B "Starts",ExUnits
  {exUnitsMem = 160, exUnitsSteps = 1624000}))])
script integrity hash: a8343f70abf9ae1169d4ac634bf4903690d2302b836ca1878a173e1bc92c5a06
txnetworkid: null
update: null
validity interval:
  invalid before: null
  invalid hereafter: null
withdrawals: []
```

It it not nicely formatted. But it allows me to find the Data map and all the redeemers.
 
My knowledge of your codebase does not allow me to understand why, the unsigned transaction can't be inspected as well.
```bash
cardano-cli view --tx-body-file tx
```
```
Command failed: transaction view  Error: tx: TextEnvelope decode error: DecoderErrorDeserialiseFailure "Shelley TxBody" (DeserialiseFailure 1 "expected tx body tuple of size 3, 4 or 6")
```
And something that did work before, getting the txid from the tx-body-file also fails with the same error. Getting txid from the signed file still works.

Happy to receive any feedback and work on this. It is also fine if you throw this away and do your own implementation. I just want this part to work.
Thank you.

### CODE REVIEW

**Comment by matiwinnetou** [comment]
WOW, this is awesome, thanks!

**Comment by cblp** [comment]
Thank you for contribution, but sorry, we went the other way, at another abstraction level https://github.com/input-output-hk/cardano-node/commit/fc7a6af4f88f9756fc8886cc21b1a45410aba31f#diff-7271ac3046a6c13ff1d3104b260169a48bcb241f39ea99c55772128e896bf9ad

**Comment by cblp** [comment]
@Titan-C do you make an unsigned transaction with `cardano-cli transaction build-raw` or any other way?

**Comment by Titan-C** [comment]
Thank you. I'll test is right away, yet I don't see how are you dealing with the collateral, datum and redeemer.

I build my transactions with "build", build-raw is too cumbersome. The issue I notified was present when I filed this PR. Today after many rebases later my patch works fine. I can preview and get the txid from unsigned transactions as from signed ones without problems.

**Comment by Titan-C** [comment]
I tested it.
I do miss the data about collateral, datum and redemer. I compiled 1.30-rc4. Until that commit none of the commits process that part of the transaction.
Also, when describing the outputs. It says "datum", whereas in this case only the "datumhash" is submitted.

**Pull request closed without merging**
