### PR TITLE
Cardano Node TODOs 2020-11-12

### PR DESCRIPTION
**Pull request by Jimbo4350**
- Add prettyPrintJSON function 
- Replace CardanoEra with ByronKeyFormat

### CODE REVIEW

**Comment by intricate** [comment]
> 121120 

What does this refer to?

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by Jimbo4350** [comment]
bors merge

**Comment by dcoutts** [comment]
Lets hold off merging before 1.24.x is sorted out. It's not essential for that release.

**Comment by dcoutts** [comment]
bors cancel

**Review by intricate — APPROVED** [review]

**Pull request merged**
