### PR TITLE
Updated ouroboros-network dependency

### PR DESCRIPTION
**Pull request by coot**
Requires input-output-hk/ouroboros-network#4067 to be reviewed and merged.

### CODE REVIEW

**Review by newhoggy — APPROVED** [review]

**Comment by michaelpj** [comment]
I'm surprised that this works, since `ouroboros-network` at the new commit seems to require a ledger commit that is not on their release branch, notably it needs the addition of `ListMap`.

**Comment by michaelpj** [comment]
It seems that both the node on `release/1.35.4` and `ouroboros-network` have updated the ledger to a commit that is not on their release branch. That seems bad.

**Comment by coot** [comment]
@michaelpj that's indeed a mistake.

**Comment by coot** [comment]
I don't see any changes in the `release/1.35.4` branch which indicate that.  @michaelpj what are you comparing with?

I double checked things related to this PR:

The `release/1.35.4` branch is using input-output-hk/ouroboros-network@c764553561bed8978d2c6753d1608dc65449617a  the same commit on which the `ouroboros-network` branch: [release/cardano-node-1.35.4](https://github.com/input-output-hk/ouroboros-network/tree/release/cardano-node-1.35.4) is based on:
```
git merge-base release/cardano-node-1.35.4 master
c764553561bed8978d2c6753d1608dc65449617a
```

The hash of `cardano-ledger` has not changed.

**Comment by michaelpj** [comment]
It's the `cardano-ledger` release branch I'm talking about. Both network and node are using commits that are not from that branch. I'm not sure what the current status of the release is, you should talk to @disassembler .

Hopefully the next major release can be done with released packages in CHaP.

**Comment by coot** [comment]
Closing this PR, the `ouroboros-network` branch `release/cardano-node-1.35.x` used by `release/1.35` branch does not require these changes.

**Pull request closed without merging**
