### PR TITLE
Optimized trace-dispatcher and tracing system

### PR DESCRIPTION
**Pull request by jutaro**
Make namespaces more opwerful, enhance the interface and have all metainformation accessible at runtime for optimizations.

### CODE REVIEW

**Review by olgahryniuk — APPROVED** [review]

**Review by deepfire — APPROVED** [review]
Thank you @jutaro !

**Comment by deepfire** [comment]
So, the problem is that analysis now produces empty results..

**Comment by deepfire** [comment]
`make ci-bench-autonix` passed and analysis data is good, merging by hand.

**Pull request merged**
