### PR TITLE
docker container: disable tagging every gitrev

### PR DESCRIPTION
**Pull request by disassembler**
Issue
-----------

-

- This PR **results**/**does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [ ] This PR contains all the work required to resolve the linked issue.

- [ ] The work contained has sufficient documentation to describe what it does and how to do it.

- [ ] The work has sufficient tests and/or testing.

- [ ] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [ ] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by islishude** [comment]
What's up?

https://github.com/input-output-hk/cardano-node/releases/tag/do-not-use
https://github.com/input-output-hk/cardano-node/releases/tag/do-not-use-2
https://github.com/input-output-hk/cardano-node/releases/tag/do-not-use-3

**Comment by sevanspowell** [comment]
I don't know enough about docker, but I believe the following lines will fail:

https://github.com/input-output-hk/cardano-node/blob/31e0190a5edf32aaca2412933c967e28d6a122d8/.buildkite/docker-build-push.nix#L59
https://github.com/input-output-hk/cardano-node/blob/31e0190a5edf32aaca2412933c967e28d6a122d8/.buildkite/docker-build-push.nix#L72

because, the docker image "$fullrepo:$gitrev" won't exist if we haven't tagged an image as such. Unless, the docker image is already named "$fullrepo:$gitrev" by default, which is the case for some repos, but not "cardano-wallet".

**Comment by sevanspowell** [comment]
> I don't know enough about docker, but I believe the following lines will fail:
> 
> https://github.com/input-output-hk/cardano-node/blob/31e0190a5edf32aaca2412933c967e28d6a122d8/.buildkite/docker-build-push.nix#L59
> 
> 
> https://github.com/input-output-hk/cardano-node/blob/31e0190a5edf32aaca2412933c967e28d6a122d8/.buildkite/docker-build-push.nix#L72
> 
> because, the docker image "$fullrepo:$gitrev" won't exist if we haven't tagged an image as such. Unless, the docker image is already named "$fullrepo:$gitrev" by default, which is the case for some repos, but not "cardano-wallet".

Yes, it seems that this repo's docker image is by default of the form "inputoutput/cardano-wallet:gitrev", see: https://buildkite.com/input-output-hk/cardano-node/builds/5030#9251f4d8-b26f-4cb8-906a-5f00450f2a38/21-57

So this should be fine.

**Comment by disassembler** [comment]
> What's up?
> 
> [`do-not-use` (release)](https://github.com/input-output-hk/cardano-node/releases/tag/do-not-use)
> [`do-not-use-2` (release)](https://github.com/input-output-hk/cardano-node/releases/tag/do-not-use-2)
> [`do-not-use-3` (release)](https://github.com/input-output-hk/cardano-node/releases/tag/do-not-use-3)

removed. Was testing automation workflow so release manager automatically publishes docker container to docker hub when release is published.

**Pull request merged**
