### PR TITLE
Add simple mainnet node script

### PR DESCRIPTION
**Pull request by Jimbo4350**

### CODE REVIEW

**Comment by edsko** [comment]
Seems to work just fine, but perhaps it'd be better to use a db in a specific directory rather than a new temp directory, created each time the script is invoked? The old mainnet script stored it in `db/byron` or some such.

**Review by edsko — APPROVED** [review]

**Review by newhoggy — APPROVED** [review]
Looks good.  Is there anything that needs to be added to `.gitignore`?

**Comment by Jimbo4350** [comment]
> Looks good. Is there anything that needs to be added to `.gitignore`?

Ah yes. Just added `/mainnet` to the `.gitignore`

**Pull request merged**
