### PR TITLE
Script data deserialisation fix and properties

### PR DESCRIPTION
**Pull request by sorki**
- Adds roundtrips for `CBOR` and `JSON` `ScriptData` encoding
- Improves generator to generate large numbers (negative and outside of `Word64` bound)
- Fixes deserialisation of `ScriptData` containing large numbers that were failing a superfluous bounds check

### CODE REVIEW

**Comment by sorki** [comment]
Ping. This is a bug in public API.

**Comment by newhoggy** [comment]
Replaced by https://github.com/input-output-hk/cardano-node/pull/5002

**Comment by newhoggy** [comment]
Merged in other PR.

**Comment by newhoggy** [comment]
Thanks for the contribution!

**Pull request closed without merging**
