### PR TITLE
Improve flake eval time, allow haskell.nix build customizations.

### PR DESCRIPTION
**Pull request by jbgi**
Also add more hydraJobs, and a profiled `nix develop` env (`nix develop .#profiled`), 
and use flake for `release.nix` and `default.nix` definition

### CODE REVIEW

**Comment by blaggacao** [comment]
I tested this in bitte-cells, it appears to keep it's promise. Please merge at earliest convenience.

**Review by blaggacao — APPROVED** [review]
Tested and working as expected on https://github.com/input-output-hk/bitte-cells

**Review by deepfire — APPROVED** [review]

**Review by disassembler — APPROVED** [review]

**Review by erikd — APPROVED** [review]

**Pull request merged**
