### PR TITLE
CAD-828 scripts:  fixes; factor; profiling; verbosity; --nix mode (new default)

### PR DESCRIPTION
**Pull request by deepfire**
1. `--nix` mode added to all scripts, and has been made the default. For the end users this will effectively make the scripts work out of the box (if they have Nix installed).

1. A Nix evaluation caching mechanism has been added to avoid costly re-evaluation, in cases where we run a certain executable several times.

1. `--profile` flag has been added;  this is end-to-end integrated with Nix, but in Cabal/Stack mode the user has to provide correspondingly built binaries for the flag to work.

1. All executable invocations now go through `scripts/lib.sh`, which means all of them are subject to the build tool choice and profiling machinery.

1. The use of configuration profiles in `configuration/defaults/*` has been further enshrined in `scripts/lib-node.sh`, which is now the code path that is used for every single `cardano-node` execution.

1. It's no longer needed to run `tmux` manually -- the `shelley-testnet` family of scripts start it on their own.

1. Verbosity-controlled tracing has been systematically planted across all the scripts.

1. CLI usage has been librified.

1. Everything has been factored and uses common code paths.
    
1. Fixes has been made to make outdated scripts work.

- This PR **does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [x] This PR contains all the work required to resolve the linked issue.

- [ ] The work contained has sufficient documentation to describe what it does and how to do it.

- [ ] The work has sufficient tests and/or testing.

- [x] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [ ] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by erikd** [comment]
Have you runs `shellcheck` over that shell code?

**Comment by deepfire** [comment]
@erikd, `scripts/*.sh` are now `shellcheck`-clean.

**Comment by deepfire** [comment]
Squashed.

**Comment by deepfire** [comment]
bors merge

**Pull request merged**
