### PR TITLE
Chairman:  allow it to fail, and add an extended failure criterion.

### PR DESCRIPTION
**Pull request by deepfire**
1. Make Chairman fail on time out.
2. Factor consensus validation spec and context data structures.
2. Make him enforce a stricter check on fork length:
   - fork lengths must remain under --maximum-fork-length
   - ..for at least --slots-within-tolerance slots

### CODE REVIEW

**Comment by CodiePP** [comment]
is this still to be merged into master at some time?

**Comment by deepfire** [comment]
@CodiePP, I think this can be retired.

**Pull request closed without merging**
