### PR TITLE
Split out cardano-testnet into its own project as a library and executable

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by newhoggy** [comment]
A future PR will add a testsuite stanza to `cardano-testnet` to test Plutus scripts.

**Review by erikd — APPROVED** [review]

**Review by Jimbo4350 — COMMENTED** [review]
README? Would be useful to have a little explanation and example usage.

**Comment by newhoggy** [comment]
There is already documentation, but I've added a README to link to it.

**Review by Jimbo4350 — APPROVED** [review]
LGTM!

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
