### PR TITLE
Shelley genesis for mainnet

### PR DESCRIPTION
**Pull request by dcoutts**
The starting point from https://github.com/input-output-hk/iohk-nix/pull/411

This is the version that was reviewed by a comittee. Changes from that point on
agreed by that review committee are individual commits.

* Set the `maxBlockHeaderSize` to 1100 bytes 

  This is the value that has been used in existing mainnet candidate
  testnets. The true value should be more like 1024, but we do not need to
  be quite so precise as this is just a DoS prevention measure.

* Change the min pool cost to 340 ada

  The min pool cost had been intended to be set to 340 ada, based on
  various calculations. Unclear why it was using a lower value.

* Change the stake address deposit to 2 ada

  The stake address deposit should be bigger than the minimum utxo value
  since it costs more resources to maintain than a UTxO entry. The min
  utxo value is 1 ada, so 2 ada is the right order of magnitude to
  correspond to the resource costs. This can be adjusted later to be more
  precise if needed.

* Remove `protocolMagicId` and `staking` entries

  The protocolMagicId is no longer used at all. Only the networkMagic is
  used. So this field is never looked at and can be removed.

  The staking field is only used when launching a chain from genesis in
  the Shelley era, not when forking from Byron. It is only used in tests
  to make it easier to set up a staking environment (pre-registering pools
  and delegations).

* Change the maxKESEvolutions from 60 to 62
  This gives just over 90 days, so a bit of leaway for people if they
  were thinking of 90 days as the target. It is less than the absolute
  maximum of 64 periods that the 2^6 KES key allows for.

* Reorder the genDelegs to be the same as in Byron

  This is not a semantic change, but it makes it easier to compare the
  Byron and Shelley genesis files by having the genensis:delegate pairs in
  the same order: 1..7, rather than 1,2,4,5,6,7,3 as it was (for no
  obvious reason).

With the current genesis file as of these changes, the hash would be
```
$ cardano-cli shelley genesis hash --genesis configuration/cardano/shelley-genesis.json
"3cc503155a18726c054fd847e0534f6cceb6e60778fbe30b1445a8006d76a4fb"
```

### CODE REVIEW

**Comment by mrBliss** [comment]
Shall we remove [`shelley-preliminary-genesis.json`](https://github.com/input-output-hk/cardano-node/blob/95ab29a03ec9c64bd8bd756835ff46342f759ccd/configuration/cardano/shelley-preliminary-genesis.json) (same folder)?

**Comment by dcoutts** [comment]
> Shall we remove shelley-preliminary-genesis.json (same folder)?

Yes we should.

**Comment by SebastienGllmt** [comment]
What was the rationale for setting `activeSlotsCoeff` to 0.05 (and then setting `slotLength` to 1 to match it) given that Jormungandr has 2 seconds?

**Comment by dcoutts** [comment]
> What was the rationale for setting activeSlotsCoeff to 0.05 (and then setting slotLength to 1 to match it) given that Jormungandr has 2 seconds?

Significantly fewer slot clashes by using the smaller `f` value. It also gives us more flexibility to adjust `f` to increase the rate of blocks if we want to, because we cannot so easily change the slot length.other end.

**Comment by dcoutts** [comment]
Last change here due to https://github.com/input-output-hk/cardano-ledger-specs/pull/1703

**Comment by dcoutts** [comment]
```$ cardano-cli shelley genesis hash --genesis configuration/cardano/shelley-genesis.json
"1a3be38bcbb7911969283716ad7aa550250226b76a61fc51cc9a9a35d9276d81"
```

**Comment by dcoutts** [comment]
bors merge

**Comment by kevinhammond** [comment]
We need to add an alternative configuration.  I will do that once I've checked the VRF keys

**Pull request merged**
