### PR TITLE
Better thread handling when starting main node action

### PR DESCRIPTION
**Pull request by coot**
`handleSimpleNode` is a non-terminating function: it can only error.  We
need to use `finally` clause to ensure that an action runs when it
errors.  It is also more pragmatic to use `withAsync` to run peer list
logging action, this way it will be cancelled once `handleSimjpleNode`
errors.  Since we don't care if that action fails we do not await on its
termination.

### CODE REVIEW

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by coot** [comment]
bors merge

**Comment by deepfire** [comment]
I don't think that `handleSimpleNode` is necessarily a non-terminating function:

- `handleSimpleNode`
- `withShutdownHandling (Node.run)`
- `withShutdownHandler`
- which is then either:
  - `Async.race_` `Node.run` 
  - `Node.run`

So when exit is requestible, it should be terminating.

**Comment by deepfire** [comment]
Basically, if `withShutdownHandling` still works as intended (which it should), the terminability of `handleSimpleNode` should depend on configuration -- whether or not one of the two ways (intra/extra-process) of termination signalling has been made active.

**Comment by coot** [comment]
The point is that `Node.run` can only error (it never terminates), if that happens clean shutdown of logging would not be executed.

**Comment by deepfire** [comment]
That is a larger, and yes -- more important point, indeed!

**Pull request merged**
