### PR TITLE
workbench: get rid of some unnecessary complications

### PR DESCRIPTION
**Pull request by fmaste**
Clearer modules dependencies. The general idea is:
> backendName -> useCabalRun -> backend
> stateDir -> batchName -> profileName -> backend -> workbench -> runner

For this:
- Moved 'services-config' back to profiles and out of the backends
- Moved the backend dependency out from 'all-profiles' (workbench)
- Removed 'stateDir' from the backends

Also:
- Remove unused code and parameters (or repeated defaults)
- Variable renames for clarity
- Makefile fixes

### CODE REVIEW

**Review by deepfire — APPROVED** [review]
This is amazing work, thank you so much @fmaste !

**Comment by deepfire** [comment]
We still need to fix the branch base & commit history.

**Comment by deepfire** [comment]
Ok, rebase fixed -- now we need `jj/update-ledger` to get merged first.

**Comment by fmaste** [comment]
bors merge

**Comment by deepfire** [comment]
No failures in the Loki log[1] -- merging by hand, since BORS is temporarily gone.

-- 
1. https://monitoring.ci.iog.io/explore?left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bnomad_alloc_id%3D%5C%22b8d07023-9b9c-c315-eea0-e42f5813eded%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D&orgId=1

**Pull request merged**
