### PR TITLE
Update to latest ouroboros-network

### LINKED ISSUE #46: Does not compile against latest ouroboros-consensus
When building against the latest master in `ouroboros-consensus`:

```
[ 7 of 10] Compiling TxSubmission

/home/nc/topos/iohk/cardano-node/app/TxSubmission.hs:228:27: error:
    • Could not deduce: Block.HeaderHash blk ~ Block.ChainHash block0
      from the context: (RunDemo blk, MonadST m)
        bound by the type signature for:
                   localChainSyncCodec :: forall blk (m :: * -> *).
                                          (RunDemo blk, MonadST m) =>
                                          NodeConfig (BlockProtocol blk)
                                          -> Codec
                                               (ChainSync blk (Point blk))
                                               DeserialiseFailure
                                               m
                                               ByteString
        at app/TxSubmission.hs:(219,1)-(223,42)
      Expected type: Block.HeaderHash blk -> Codec.CBOR.Encoding.Encoding
        Actual type: Block.ChainHash block0
                     -> Codec.CBOR.Encoding.Encoding
      The type variable ‘block0’ is ambiguous
    • In the first argument of ‘Block.encodePoint’, namely
        ‘(Block.encodeChainHash demoEncodeHeaderHash)’
      In the third argument of ‘codecChainSync’, namely
        ‘(Block.encodePoint (Block.encodeChainHash demoEncodeHeaderHash))’
      In the expression:
        codecChainSync
          (demoEncodeBlock pInfoConfig)
          (demoDecodeBlock pInfoConfig)
          (Block.encodePoint (Block.encodeChainHash demoEncodeHeaderHash))
          (Block.decodePoint (Block.decodeChainHash demoDecodeHeaderHash))
    • Relevant bindings include
        pInfoConfig :: NodeConfig (BlockProtocol blk)
          (bound at app/TxSubmission.hs:224:21)
        localChainSyncCodec :: NodeConfig (BlockProtocol blk)
                               -> Codec
                                    (ChainSync blk (Point blk)) DeserialiseFailure m ByteString
          (bound at app/TxSubmission.hs:224:1)
    |
228 |       (Block.encodePoint (Block.encodeChainHash demoEncodeHeaderHash))
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by nc6**
Fixes #46

### CODE REVIEW

**Comment by nc6** [comment]
@mrBliss What do you mean fix the wallet client? The executable here is fixed. Is that in another repo again?

**Comment by mrBliss** [comment]
> @mrBliss What do you mean fix the wallet client? The executable here is fixed. Is that in another repo again?

CI is failing in `wallet-client/WalletClient.hs`: https://hydra.iohk.io/build/944470/nixlog/3

**Comment by nc6** [comment]
Ah, I have failed to do the old `nix/regenerate.sh` malarkay...

**Comment by mrBliss** [comment]
And `cabal.project` should also be updated. @erikd would be happy if you used the cardano-repo-tool :slightly_smiling_face:

**Comment by mrBliss** [comment]
Whoever gets to merge this, don't forget to squash first.

**Pull request merged**
