### PR TITLE
Bench nix refactoring

### PR DESCRIPTION
**Pull request by fmaste**
Cleanups and refactorings that are needed to add the `Docker` backend alongside the `supervisord` backend

- Make backend files (here only `supervisor.nix`) as independent as possible.
- Created a backend subfolder.
- Extracted the code used as configuration for `generator-service`, `node-services` and `tracer-service` outside of the specific backend.
- Remove unused code in the process.

By looking at the individuals commits you can see the approach taken to evolve the code. Small/atomic steps and too much testing. History is for review purposes only, it's intended to be squashed when merged!

### CODE REVIEW

**Review by deepfire — APPROVED** [review]
Thank you a ton @fmaste !

:heart:

**Review by Jimbo4350 — APPROVED** [review]

**Comment by fmaste** [comment]
bors merge

**Comment by fmaste** [comment]
bors merge

**Pull request merged**
