### PR TITLE
API fixes for the automated tx building

### PR DESCRIPTION
**Pull request by dcoutts**
The commits in this PR are extracted from the first commit in Jordan's PR #2921.

It is split out for easier review to see what is really changing, and it omits some of
the unnecessary changes, plus my opinionated code review.

### CODE REVIEW

**Comment by dcoutts** [comment]
Importantly this does not include the workaround from the original PR for the problem that we are apparently not calculating the correct fee. The workaround in the original PR was to use the ledger's `evaluateTransactionFee` function and then to separately calculate the contribution to the fees arising from the execution units. We clearly should not need such a workaround. If `evaluateTransactionFee` is not including the contribution to the fees coming from the execution units then that should be fixed upstream. At first glance it looks like the ledger `evaluateTransactionFee` is actually using the exunits properly. So if it's some other bug, then that needs to be understood and fixed.

https://github.com/input-output-hk/cardano-node/pull/2921#pullrequestreview-712232263

**Review by Jimbo4350 — APPROVED** [review]
These changes look right :+1:

**Comment by dcoutts** [comment]
Ok, so we now think `evaluateTransactionFee` may actually be right, and it was other bugs (since resolved) that needed the workaround.

**Comment by dcoutts** [comment]
bors merge

**Pull request merged**
