### PR TITLE
Replace panic with fail in JSON parsers

### PR DESCRIPTION
**Pull request by newhoggy**
Attempt to take https://github.com/input-output-hk/cardano-node/pull/1955 to fruition

Replace panic with fail in JSON parsers in:

* Cardano.Node.Types
* Cardano.Node.Orphans
* Cardano.Tracing.OrphanInstances.Common

### CODE REVIEW

**Review by Jimbo4350 — APPROVED** [review]

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by dcoutts** [comment]
bors merge

**Review by intricate — APPROVED** [review]

**Pull request merged**
