### PR TITLE
Add tulia task that run system tests on PRs

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
Which QA tests? There needs to be some documentation around this to understand which tests are run.

**Comment by jbgi** [comment]
@Jimbo4350 with this PR no tests will be run. It's a first step to be able to later plug-in some tests into the cicero tasks DAG.

The actual tests list is being work-on by QA team. @mkoura should be more explicit about what QA team want to run on each PR.

**Comment by dorin100** [comment]
> Which QA tests? There needs to be some documentation around this to understand which tests are run.

I will work this week on a short documentation for these tests/pipelines.

**Comment by mkoura** [comment]
I'm not sure what setup is done by tullia. For QA tests you can run smtg like
```
NODE_REV=ee4cfdd0001fb7d211cdcabe84d3e532d3f6e7ad ENABLE_P2P=1 UPDATE_PV8=1 MAKE_TARGET=testpr ./.github/regression.sh
```
from cardano-node-tests repo and it will launch tests in nix shell with correct environment. The script prepares the environment and launches `make testpr`.

**Review by Jimbo4350 — APPROVED** [review]

**Pull request merged**
