### PR TITLE
Switch default era to Babbage

### PR DESCRIPTION
**Pull request by newhoggy**
Code changes required for https://github.com/input-output-hk/cardano-node/issues/4151

### CODE REVIEW

**Review by LudvikGalois — APPROVED** [review]

**Comment by newhoggy** [comment]
Verifying that `transaction build` works.

Commands:

```
CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) query utxo \
  --testnet-magic 42 \
  --address $( \
    cardano-cli address build \
      --testnet-magic 42 \
      --payment-verification-key-file \
      example/utxo-keys/utxo1.vkey
  ) \
  --out-file utxo.json

user1_utxo="$(cat utxo.json | jq -r 'to_entries[0].key')"
user1_addr="$(cat utxo.json | jq -r 'to_entries[0].value.address')"

CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) transaction build \
  --testnet-magic 42 \
  --change-address "${user1_addr}" \
  --tx-in "${user1_utxo}" \
  --tx-out "${user1_addr}+1000000" \
  --out-file tx.body

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction sign --tx-body-file tx.body --signing-key-file example/utxo-keys/utxo1.skey --out-file tx.body.signed

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction submit --tx-file tx.body.signed --testnet-magic 42
```

Output:
```
Estimated transaction fee: Lovelace 165721
Transaction successfully submitted.
```

**Comment by newhoggy** [comment]
Verifying that `transaction build` works with `--babbage-era` flag.

Commands:

```
CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) query utxo \
  --testnet-magic 42 \
  --address $( \
    cardano-cli address build \
      --testnet-magic 42 \
      --payment-verification-key-file \
      example/utxo-keys/utxo1.vkey
  ) \
  --out-file utxo.json


user1_utxo="$(cat utxo.json | jq -r 'to_entries[0].key')"
user1_addr="$(cat utxo.json | jq -r 'to_entries[0].value.address')"

CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) transaction build \
  --babbage-era \
  --testnet-magic 42 \
  --change-address "${user1_addr}" \
  --tx-in "${user1_utxo}" \
  --tx-out "${user1_addr}+1000000" \
  --out-file tx.body

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction sign --tx-body-file tx.body --signing-key-file example/utxo-keys/utxo1.skey --out-file tx.body.signed

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction submit --tx-file tx.body.signed --testnet-magic 42
```

Output:
```
Estimated transaction fee: Lovelace 165721
Transaction successfully submitted.
```

**Comment by newhoggy** [comment]
Verifying that `transaction build-raw` works with `--babbage-era` flag.

```
mkdir example/work

CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) query utxo \
  --testnet-magic 42 \
  --address $( \
    cardano-cli address build \
      --testnet-magic 42 \
      --payment-verification-key-file \
      example/utxo-keys/utxo1.vkey
  ) \
  --out-file example/work/utxo.json


user1_utxo="$(cat example/work/utxo.json | jq -r 'to_entries[0].key')"
user1_addr="$(cat example/work/utxo.json | jq -r 'to_entries[0].value.address')"
user1_fund="$(cat example/work/utxo.json | jq -r 'to_entries[0].value.value.lovelace')"

fee=550152

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli query protocol-parameters --testnet-magic 42 > example/work/params.json

cardano-cli transaction build-raw \
  --babbage-era \
  --fee "$fee" \
  --out-file example/tx.body \
  --protocol-params-file example/work/params.json \
  --tx-in "$user1_utxo" \
  --tx-out "$user1_addr+$(($user1_fund - $fee"))"

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction sign --tx-body-file example/tx.body --signing-key-file example/utxo-keys/utxo1.skey --out-file example/tx.body.signed

CARDANO_NODE_SOCKET_PATH=example/main.sock cardano-cli transaction submit --tx-file example/tx.body.signed --testnet-magic 42

**Comment by newhoggy** [comment]
Verifying that `transaction calculate-min-required-utxo` works without era flag.

```
mkdir -p example/work

CARDANO_NODE_SOCKET_PATH=example/main.sock \
$(./scripts/bin-path.sh cardano-cli) query utxo \
  --testnet-magic 42 \
  --address $( \
    cardano-cli address build \
      --testnet-magic 42 \
      --payment-verification-key-file \
      example/utxo-keys/utxo1.vkey
  ) \
  --out-file example/work/utxo.json


user1_utxo="$(cat example/work/utxo.json | jq -r 'to_entries[0].key')"
user1_addr="$(cat example/work/utxo.json | jq -r 'to_entries[0].value.address')"
user1_fund="$(cat example/work/utxo.json | jq -r 'to_entries[0].value.value.lovelace')"

cardano-cli transaction calculate-min-required-utxo --babbage-era --protocol-params-file example/work/params.json --tx-out "$user1_addr+0"
```

Result:

```
Lovelace 840450
```

**Review by Jimbo4350 — APPROVED** [review]
LGTM

**Pull request merged**
