### PR TITLE
Update: fix ValueNotConservedUTxO serialization

### PR DESCRIPTION
**Pull request by mrBliss**
This updates the dependencies on `cardano-ledger-specs` and `ouroboros-network`
to bring in https://github.com/input-output-hk/cardano-ledger-specs/pull/1955

Other visible change: https://github.com/input-output-hk/ouroboros-network/pull/2714

### CODE REVIEW

**Comment by mrBliss** [comment]
Draft because https://github.com/input-output-hk/ouroboros-network/pull/2719 hasn't been merged yet.

**Comment by mrBliss** [comment]
If we want compatibility with GHC 8.6.5, https://github.com/input-output-hk/cardano-ledger-specs/pull/1956 needs to be merged and the dependency on it needs to be bumped in this repo. Unless anything breaking is merged before that PR, the change doesn't have to be propagated to `ouroboros-network` first.

**Review by dcoutts — APPROVED** [review]
LGTM.

**Comment by mrBliss** [comment]
Both https://github.com/input-output-hk/ouroboros-network/pull/2719 and https://github.com/input-output-hk/cardano-ledger-specs/pull/1956 have been merged, so we can merge this PR too.

**Comment by mrBliss** [comment]
bors merge

**Pull request merged**
