### PR TITLE
Remove genesis-hash and genesis-file arguments from cardano-node

### PR DESCRIPTION
**Pull request by Jimbo4350**
Issue
-----------

- #613 

- This PR **results** in breaking changes to upstream dependencies.

Checklist
---------
- [x] This PR contains all the work required to resolve the linked issue.

- [ ] The work contained has sufficient documentation to describe what it does and how to do it.

- [ ] The work has sufficient tests and/or testing.

- [x] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [x] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by erikd** [comment]
I assume that these can still be overridden on the command line.

**Comment by rhyslbw** [comment]
@erikd 
> I assume that these can still be overridden on the command line. If so
```
Invalid option `--genesis-file'

Usage: cardano-node run --topology FILEPATH --database-path FILEPATH
                        [--delegation-certificate FILEPATH]
                        [--signing-key FILEPATH] [--socket-path FILEPATH]
                        [--host-addr HOST-NAME] --port PORT
                        --config NODE-CONFIGURATION [--validate-db]
```

**Comment by Jimbo4350** [comment]
@erikd @rhyslbw It was my understanding that we wanted to reduce the number of arguments needed for `cardano-node`. DevOps wanted still wanted the  ability to specify socket-path from the command line (which remains but defaults to what is in the configuration yaml file if nothing is specified). It doesn't make sense to specify genesis-hash from the command line because we can derive the genesis hash from the genesis file. 

So the question is, am I completely removing the ability to specify the genesis file from the command line (i.e it will be defined in the configuration yaml file) or am I leaving the ability to specify the genesis file on the command line (i.e if is it specified, it will override whatever is in the configuration yaml file)?

**Pull request merged**
