### PR TITLE
Sync with cardano-ledger and ouroboros-network

### PR DESCRIPTION
**Pull request by dcoutts**
Fix API change in use of Dummy.dummyConfig and the dummy/testing generated secrets.
    
Fix API changes in the consensus ChainDB tracers, and EpochInfo.

### CODE REVIEW

**Comment by mrBliss** [comment]
Also see #104

**Comment by dcoutts** [comment]
Oh, the compile error mean either waiting for https://github.com/input-output-hk/ouroboros-network/pull/907 or rolling back to a slightly earlier commit.

Probably better to wait and incorporate #104 too.

**Pull request merged**
