### PR TITLE
Don't trace the updated chain

### PR DESCRIPTION
**Pull request by mrBliss**
Addresses #59.

IMO, #57 is a more readable way to trace the chain.

### CODE REVIEW

**Comment by 365andreas** [comment]
@mrBliss You need to rebase your branch on master.

**Comment by 365andreas** [comment]
bors try

**Comment by mrBliss** [comment]
> @mrBliss You need to rebase your branch on master.

Indeed, I realised it after the first failure and I thought I fixed it then, but apparently not.

**Comment by mrBliss** [comment]
btw, I *had* rebased on top of master, but you cancelled bors.

**Comment by 365andreas** [comment]
Ok do not worry. I will take care of it.

**Comment by 365andreas** [comment]
bors try-

**Pull request merged**
