### PR TITLE
add hydra windows build artifact

### PR DESCRIPTION
**Pull request by disassembler**
Issue
-----------

-

- This PR **results**/**does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [ ] This PR contains all the work required to resolve the linked issue.

- [ ] The work contained has sufficient documentation to describe what it does and how to do it.

- [ ] The work has sufficient tests and/or testing.

- [ ] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [ ] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by dcoutts** [comment]
Should this go before/after #669?

**Comment by disassembler** [comment]
bors+

**Comment by disassembler** [comment]
bors ping

**Pull request merged**
