### PR TITLE
Release 1.24.1

### PR DESCRIPTION
**Pull request by dcoutts**
Pull in one fix in consensus and one fix in ledger.

### CODE REVIEW

**Comment by dcoutts** [comment]
This depends on https://github.com/input-output-hk/ouroboros-network/pull/2788 getting merged.

The commit hash will need to be updated once it is, to point to the commit on the `master` branch for `ouroboros-network`.

**Comment by rvl** [comment]
Could we please get #2161 in before the tagging?

**Comment by dcoutts** [comment]
input-output-hk/ouroboros-network#2788 has merged.

Updated this PR to take the ouroboros-network commit from `master`.

@rvl Cherry-picked the haddock fix from #2161.

**Review by mrBliss — APPROVED** [review]
LGTM

**Comment by dcoutts** [comment]
bors merge

**Comment by dcoutts** [comment]
bors merge

**Comment by dcoutts** [comment]
bors merge

**Review by intricate — APPROVED** [review]

**Pull request merged**
