### PR TITLE
Remove old chairman

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by Jimbo4350** [comment]
Is the new chairman running in CI?

**Comment by newhoggy** [comment]
> Just confirming that the new chairman running in CI

Yep.  It also runs for Windows and MacOS in CI.  😁

**Review by deepfire — APPROVED** [review]

**Comment by newhoggy** [comment]
This is already removed by https://github.com/input-output-hk/cardano-node/pull/2018

**Pull request closed without merging**
