### PR TITLE
Update feature_request.md

### PR DESCRIPTION
**Pull request by kevinhammond**
Added Plutus scripts (Alonzo)

### CODE REVIEW

**Comment by Jimbo4350** [comment]
@kevinhammond I'll approve after the commits are squashed

**Review by CodiePP — APPROVED** [review]
:+1:

**Comment by Jimbo4350** [comment]
> squashing of the commits can be done while merging. just check the options on the "merge" button.

We use `bors` to merge in this repo

**Comment by james-iohk** [comment]
bors merge

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
Please squash the commits

**Review by Jimbo4350 — APPROVED** [review]

**Pull request merged**
