### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dcoutts**

### CODE REVIEW

**Comment by dcoutts** [comment]
need to update sha256 hashes, versions and changelog...

**Comment by mrBliss** [comment]
@dcoutts I would like to get https://github.com/input-output-hk/ouroboros-network/pull/1787 in this release. It should fix https://github.com/input-output-hk/cardano-node/issues/651. I'm still waiting on bors, though...

**Comment by dcoutts** [comment]
Waiting on https://github.com/input-output-hk/ouroboros-network/pull/1787 and https://github.com/input-output-hk/ouroboros-network/pull/1800

**Pull request merged**
