### PR TITLE
Colors in cli output

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by newhoggy** [comment]
Removes the following redundant parentheses:

```
$ cardano-cli transaction build-raw ...
Missing:  (--tx-in TX-IN )  ( )

Usage: cardano-cli transaction build-raw
            [ --byron-era
            ...
```

**Comment by newhoggy** [comment]
Adds a splash of colour to demonstrate that the forked version of `optparse-applicative` supports ANSI colours.

image

**Review by erikd — APPROVED** [review]

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
bors merge

**Review by MarcFontaine — APPROVED** [review]
LGTM

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
