### PR TITLE
Use ouroboros-network-0.3.0.2 and ouroboros-network-framework-0.2.0.1

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Review by Jimbo4350 — APPROVED** [review]

**Review by disassembler — APPROVED** [review]

**Comment by coot** [comment]
bors merge

**Comment by disassembler** [comment]
Bors r+

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
CI on `staging` finished (https://github.com/input-output-hk/cardano-node/commit/ce110033f35e1578df317503d602b7daa7650d43), but bors is s till pending.

The `bors.toml` file contains:
```toml
status = [
  "ci/pr/required",
]
```
but I don't see something like that in cicero, there's `ci/pr/nix/required` though.  It might be doomed to timeout.

**Comment by coot** [comment]
In `master` the `ci/pr/required` check was removed from `bors.toml` in PR #4923.

**Comment by dermetfan** [comment]
bors merge

**Pull request merged**
