### PR TITLE
Remove changelog from extra-source-files.  This is necessary for 'cabal install' to work

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Review by mrBliss — COMMENTED** [review]
If there is no `ChangeLog.md` and the tool itself is not meant for public use, I would remove the `extra-source-files:     ChangeLog.md` line from the cabal file instead of adding an empty `ChangeLog.md`.

**Comment by newhoggy** [comment]
Removed as suggested.

**Review by mrBliss — APPROVED** [review]
Thanks for taking care of this!

**Comment by newhoggy** [comment]
Thanks!

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
