### PR TITLE
Remove cardano-config

### PR DESCRIPTION
**Pull request by Jimbo4350**

### CODE REVIEW

**Review by newhoggy — APPROVED** [review]

**Review by rvl — APPROVED** [review]

**Comment by newhoggy** [comment]
There's an error in CI:

```
<no location info>: error:
    <command line>: can't load .so/.DLL for: libHScardano-api-1.19.1-9lA2untDJmALfxneTVdNlH.so (Error loading shared library libHScardano-api-1.19.1-9lA2untDJmALfxneTVdNlH.so: No such file or directory)
```

**Comment by rvl** [comment]
Hmm strange that this error appears just because the code was moved. It seems to be due to template haskell on the cross-compiled musl build.

**Comment by Jimbo4350** [comment]
> Hmm strange that this error appears just because the code was moved. It seems to be due to template haskell on the cross-compiled musl build.

I've run into this before but I have no idea how to fix it. How did you figure this out?

**Comment by rvl** [comment]
@Jimbo4350 Sorry, after another look at this, I still don't know what is wrong. All that is different from before is that the `Git.Rev` module is now in the same package where it's used, and there are now two copies of it (under `Cardano` and `Cardano.CLI`). @angerman might have some ideas.

**Comment by Jimbo4350** [comment]
Closing as we currently cannot figure out why CI is failing

**Pull request closed without merging**
