### PR TITLE
Fix recursion in flake inputs.

### LINKED ISSUE #4525: [BUG] - Hydra: `error: cannot update flake input 'cardano-node/cardano-node-workbench/membench' in pure mode`
**Internal/External**
*External*

**Area**
Nix

**Summary**
Hydra gives out this evaluation error when trying to evaluate a flake containing `cardano-node` as input.

```
hydra-eval-jobs returned exit code 1:
error: cannot update flake input 'cardano-node/cardano-node-workbench/membench' in pure mode
error: worker error: error: cannot update flake input 'cardano-node/cardano-node-workbench/membench' in pure mode
```
It looks like it tries to lock some inputs (but they should be all specified in the lockfile) but fails it Hydra works in pure mode.

Maybe this is due to its weird "recursive" inputs which also causes this warning using Nix from CLI:
```
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-measured'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-process'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'cardano-node-snapshot'
warning: input 'cardano-node/node-measured/node-measured/cardano-node-workbench/membench' has an override for a non-existent input 'nixpkgs'
``` 

Or maybe this is an error in Nix (or Hydra?) itself that can't manage `follows` as it should.

**Steps to reproduce**
Create a flake with `cardano-node` as input and add it to Hydra.

**Expected behavior**
It just works.

**System info (please complete the following information):**
- OS Name: NixOS
- OS Version 22.11
- Nix version: 2.9.1
- Hydra version: 0.1.20220820
- Node version: should be 1.35.3 (my flake input is `cardano-node/a0b000380a32155feb62d3bfd73513243c98a4f6`) 

**Additional context**
In case this was a bug in Hydra or Nix I think that IOG is using some workaround to make their stuff build on Hydra (or maybe IOG doesn't use Hydra? TBH I've no idea), maybe someone could share it here?
I tried adding several `following` to my inputs to be sure that they are locked but I had no luck.

### PR DESCRIPTION
**Pull request by andreabedini**
hydra-eval-jobs seems to have trouble evaluating this flake.

  error: cannot update flake input 'cardano-node-workbench/membench' in pure mode

Simplifying the recursion in the flake inputs seems to help.

Fixes #4525

### CODE REVIEW

**Review by angerman — APPROVED** [review]
Nice! 👍 

Let's see what CI says.

**Comment by angerman** [comment]
I think this is good to go. Only the non-required fail, which have been failing for a while, and should be broken out in a separate PR to fix.

**Comment by angerman** [comment]
bors try

**Comment by andreabedini** [comment]
bors merge

**Pull request merged**
