### PR TITLE
Remove unused test dependencies

### PR DESCRIPTION
**Pull request by mrBliss**
These dependencies are no longer needed. The benefit is that we'll have less hashes to (manually) update.

- This PR **does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [ ] This PR contains all the work required to resolve the linked issue.

- [X] The work contained has sufficient documentation to describe what it does and how to do it.

- [ ] The work has sufficient tests and/or testing.

- [X] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [X] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by mrBliss** [comment]
#710 will disable tests for dependencies and drop the redundant test dependencies.

**Comment by dcoutts** [comment]
Actually it will not, I'll update this PR for that instead.

**Comment by dcoutts** [comment]
This can be rebased after #710 is merged.

Note that I expect the docker build test to fail. This is a problem with how we're building that. It looks like it forces the `--enable-tests` to be on on the command line, which then undoes all the good work done in this PR to avoid building the tests of dependencies.

If anyone can figure out where that `--enable-tests` is sneaking in and eliminate it, that'd be great, thanks.

**Comment by mrBliss** [comment]
No longer needed since #806.

**Pull request closed without merging**
