### PR TITLE
CAD-413: Update ouroboros-network dependency.

### PR DESCRIPTION
**Pull request by denisshevchenko**
Update `ouroboros-network` dependency, after merging latest PRs which fix some problems.

### CODE REVIEW

**Comment by mrBliss** [comment]
You have to update the nix dependencies as well.

**Comment by denisshevchenko** [comment]
@mrBliss Done.

**Comment by denisshevchenko** [comment]
> Why is the cardano-explorer submodule bumped?

I don't know, it was done automatically, I only changed dependencies. How can I remove it from this commit?

**Pull request merged**
