### PR TITLE
Upgrade to ghc-8.10.3 in Github Actions

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by newhoggy** [comment]
Disabling this test:

```
    Actions tests
      test AlterSeverity:                                                                               FAIL
        Exception: ExceptionInLinkedThread (ThreadId 29) thread blocked indefinitely in an STM transaction
```

This is a known issue in `iohk-monitoring`: https://github.com/input-output-hk/iohk-monitoring-framework/pull/615/checks?check_run_id=2016476213

**Comment by erikd** [comment]
Probably need to figure out why that exception is being thrown in `iohk-monitoring`. Would you be able to figure that out?

**Comment by newhoggy** [comment]
> Probably need to figure out why that exception is being thrown

I believe @deepfire is aware of it and has a plan to fix it.

**Comment by newhoggy** [comment]
@deepfire can you notify us when it's fixed, so I can re-enable the test in `cardano-node`?

**Comment by erikd** [comment]
@newhoggy I think in general tests that are not in this repo should not be run when running PRs for this repo through CI.

**Comment by coot** [comment]
Why not use `ghc-8.10.4`?

**Comment by newhoggy** [comment]
> Why not use ghc-8.10.4?

I will be trying `ghc-8.10.4` next.  That one is known to fail, so I wanted to get this working first.

**Review by Jimbo4350 — APPROVED** [review]

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
