### PR TITLE
CAD-2907: add locli

### PR DESCRIPTION
**Pull request by deepfire**
This adds the `locli` log analysis tool to `nix/workbench`, and integrates it.

### CODE REVIEW

**Review by newhoggy — APPROVED** [review]

**Comment by Jimbo4350** [comment]
Sorry @deepfire , can you change the name space?  `Cardano.` -> `Nix.Cardano.` or something similar?

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
Simple name space change

**Review by Jimbo4350 — APPROVED** [review]

**Pull request merged**
