### PR TITLE
Script ToJSON instances serialises the full script

### PR DESCRIPTION
**Pull request by abailly-iohk**
There used to be no orphan instance for ledger Script so we (Hydra)
provided our own. This newly introduced instance overlaps with our own
which would not be a problem, as we are fine using upstream instances,
but for the fact the serialisation is lossy as cardano-api only
serialised the hash of the script.

### CODE REVIEW

**Comment by abailly-iohk** [comment]
Note this is an alternative to #4130 which is less principled (still has orphan instance in a place there should be none) but easier to integrate.

**Comment by abailly-iohk** [comment]
@Jimbo4350 I am trying to update my PR to address comments you made on @ch1bo 's PR #4130, but not sure what's the best approach. There's currently a `Shelley.Orphans` module in the cardano-cli, do you want me to create a `Babbage.Orphans` module that would contain this script instance?

**Review by dcoutts — APPROVED** [review]
Looks reasonable to me.

**Comment by dcoutts** [comment]
Oh I see I should have approved #4223 which is the version rebased on the master branch.

**Review by Jimbo4350 — APPROVED** [review]
LGTM, can you squash the commits?

**Comment by ch1bo** [comment]
@Jimbo4350 would need to open another branch on origin for that. I have squashed & rebased on the master PR. We would love to get it after `master` also onto `release/1.35` but not sure what the policy is.

**Comment by ch1bo** [comment]
This change was merged now on `master`. Shall we close this and cherry-pick the commit from `master` onto `release/1.35` instead?

**Comment by newhoggy** [comment]
Looks like this has already been merged into the release branch.  Closing.

**Pull request closed without merging**
