### PR TITLE
Introduce `NodeConfiguration`

### PR DESCRIPTION
**Pull request by Jimbo4350**
The overall goal is to have `cardano-node` accept a `--config-file` parameter that will determine logging, tracing and general node settings (protocol, slot length etc). 

I.E. move all the `cardano-node` configuration arguments from the command line (with the exception of specifying filepaths for various things e.g `mainnet-genesis.json`) to the `log-configuration.yaml` file. 

**NB**: This does not apply to the cli which will continue to use the POM approach.

This PR takes the first step by:
- Introducing `NodeConfiguration` which is meant to replace any usage of `CardanoConfiguration` in starting up the node.
- Modifying `log-configuration.yaml` to include various node settings.

### CODE REVIEW

**Comment by deepfire** [comment]
@Jimbo4350, can I have a radical suggestion? : -)

Perhaps the `Cardano` is implied, and so the name could be shortened to just `NodeConfiguration`.

We want to maximise meaning-per-character efficiency of our names (implying no loss of readability), and `Cardano` is sort-of implied for the entire project.

**Comment by Jimbo4350** [comment]
`parseRepresentation` lives in `iohk-monitoring-framework`
> Jordan showed in a conversation that the parsing of the logging configuration still works even with the extra bits from the node's config added to it.

```
parseRepresentation "../configuration/log-configuration.yaml"
Representation {minSeverity = Debug, rotation = Just (RotationParameters {rpLogLimitBytes = 5000000, rpMaxAgeHours = 24, rpKeepFilesNum = 10}), setupScribes = [ScribeDefinition {scKind = StdoutSK, scFormat = ScText, scName = "stdout", scPrivacy = ScPublic, scRotation = Nothing}], defaultScribes = [(StdoutSK,"stdout")], setupBackends = [AggregationBK,KatipBK], defaultBackends = [KatipBK], hasEKG = Nothing, hasGraylog = Nothing, hasPrometheus = Nothing, hasGUI = Nothing, logOutput = Nothing, options = fromList [("mapSubtrace",fromList [("cardano.epoch-validation.utxo-stats",Object (fromList [("subtrace",String "NoTrace")])),("benchmark",Object (fromList [("contents",Array [String "GhcRtsStats",String "MonotonicClock"]),("subtrace",String "ObservableTrace")])),("#ekgview",Object (fromList [("contents",Array [Array [Object (fromList [("tag",String "Contains"),("contents",String "cardano.epoch-validation.benchmark")]),Array [Object (fromList [("tag",String "Contains"),("contents",String ".monoclock.basic.")])]],Array [Object (fromList [("tag",String "Contains"),("contents",String "cardano.epoch-validation.benchmark")]),Array [Object (fromList [("tag",String "Contains"),("contents",String "diff.RTS.cpuNs.timed.")])]],Array [Object (fromList [("tag",String "StartsWith"),("contents",String "#ekgview.#aggregation.cardano.epoch-validation.benchmark")]),Array [Object (fromList [("tag",String "Contains"),("contents",String "diff.RTS.gcNum.timed.")])]]]),("subtrace",String "FilterTrace")])),("#messagecounters.ekgview",Object (fromList [("subtrace",String "NoTrace")])),("#messagecounters.aggregation",Object (fromList [("subtrace",String "NoTrace")])),("#messagecounters.switchboard",Object (fromList [("subtrace",String "NoTrace")]))]),("cfokey",fromList [("value",String "Release-1.0.0")]),("mapBackends",fromList [("cardano.epoch-validation.benchmark",Array [String "AggregationBK"]),("#aggregation.cardano.epoch-validation.benchmark",Array [String "EKGViewBK"])])]}
```

**Pull request merged**
