### PR TITLE
Fix mkfiles.sh

### PR DESCRIPTION
**Pull request by Jimbo4350**

### CODE REVIEW

**Comment by DavidEichmann** [comment]
What's prompted this change? Note that `genesis/genesis.spec.json` on master currently has `"decentralisationParam": 0.99,` not `"decentralisationParam": 1.0`.

**Review by erikd — APPROVED** [review]

**Comment by Jimbo4350** [comment]
>What's prompted this change? Note that genesis/genesis.spec.json on master currently has "decentralisationParam": 0.99, not "decentralisationParam": 1.0.

@JaredCorduan did the cost model changes also affect the `decentralisationParam`?

**Review by newhoggy — APPROVED** [review]

**Comment by JaredCorduan** [comment]
> > What's prompted this change? Note that genesis/genesis.spec.json on master currently has "decentralisationParam": 0.99, not "decentralisationParam": 1.0.
> 
> @JaredCorduan did the cost model changes also affect the `decentralisationParam`? This script was working before the recent cost model changes.

No, the fractional pricing would have no effect on `d`.

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
