### PR TITLE
Remove IPv6 options and make the host IP address omniversioned

### PR DESCRIPTION
**Pull request by cblp**

### CODE REVIEW

**Review by karknu — CHANGES_REQUESTED** [review]
This removes the support for nodes running both IPv4 and IPv6 at the same time with manually configured addresses.

**Comment by cblp** [comment]
@karknu is it a documented feature to run the node on multiple IP interfaces?

**Comment by JamesRobertKelley** [comment]
> @karknu is it a documented feature to run the node on multiple IP interfaces?

I was wondering if it would be possible to bind the cardano-node to multiple IPs because I'm getting a Starlink dish soon and was going to multihome the server so that it would communicate on both the Starlink and local cable Internet (because Starlink is in beta and may drop connections).

**Comment by coot** [comment]
^ @karknu is it a documented feature to run the node on multiple IP interfaces?

This feature is independent whether one is using multiple interfaces or not.

^ I was wondering if it would be possible to bind the cardano-node to multiple IPs

We are not supporting this at the moment, beside allowing to configure different `ipv6` and `ipv4` addresses / ports which may or may not be served by a different interface.  We might support multiple inbound addresses in the future.

**Comment by cblp** [comment]
wrong direction

**Pull request closed without merging**
