### PR TITLE
Use of the optional was redundant because flag function already implies optionality

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Review by olgahryniuk — APPROVED** [review]

**Review by Jimbo4350 — DISMISSED** [review]
So as excited as I am to review this gigantic diff I assume you meant to PR this to the release branch?

**Comment by newhoggy** [comment]
Yep.  My mistake.  I have changed the merge target.

**Review by Jimbo4350 — APPROVED** [review]

**Pull request closed without merging**
