### PR TITLE
Also install libnuma-dev and llvm packages

### PR DESCRIPTION
**Pull request by weebl2000**
I could not build without these.

### CODE REVIEW

**Comment by weebl2000** [comment]
@coot AFAIK libnuma-dev and llvm packages are required to build cardano-node. Can we merge this?

**Comment by Jimbo4350** [comment]
@weebl2000 can you rebase on master? I will approve and merge after.

**Comment by weebl2000** [comment]
> @weebl2000 can you rebase on master? I will approve and merge after.

yes sir

**Comment by weebl2000** [comment]
> @weebl2000 can you rebase on master? I will approve and merge after.

Done!

**Review by olgahryniuk — APPROVED** [review]

**Comment by Jimbo4350** [comment]
Subsumed by #4567

**Comment by newhoggy** [comment]
@weebl2000 it shouldn't be the case that those to packages are required to build `cardano-node`.  Can you paste the error message you get if you try to build `cardano-node` without them?

**Comment by weebl2000** [comment]
```
rts/posix/OSMem.c:370:0: error:
     error: undefined reference to 'mbind'

rts/posix/OSMem.c:739:0: error:
     error: undefined reference to 'numa_available'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSMem.c:758:0: error:
     error: undefined reference to 'numa_get_mems_allowed'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSMem.c:763:0: error:
     error: undefined reference to 'numa_bitmask_free'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSThreads.c:368:0: error:
     error: undefined reference to 'numa_run_on_node'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

```

**Comment by newhoggy** [comment]
Thanks for the information.  Can you compile `cardano-node` with `-j1` so it is more obvious which Haskell package is failing to compile?

**Comment by angerman** [comment]
@weebl2000 do you obtain your ghc through GHCup or some other way?

**Comment by angerman** [comment]
Then again, if the bindists pulled by GHCup have numa enabled, I can see why libnuma would be required for linking. I don't understand why we need llvm though?

**Comment by weebl2000** [comment]
> @weebl2000 do you obtain your ghc through GHCup or some other way?

Yes, ghcup.

> Thanks for the information. Can you compile `cardano-node` with `-j1` so it is more obvious which Haskell package is failing to compile?

Like this?

`Building executable 'cardano-cli' for cardano-cli-1.35.3..
Linking /data/cardano/src/cardano-node/dist-newstyle/build/aarch64-linux/ghc-8.10.7/cardano-cli-1.35.3/x/cardano-cli/build/cardano-cli/cardano-cli ...
/usr/bin/ld.gold: error: cannot find -lnuma

rts/posix/OSMem.c:370:0: error:
     error: undefined reference to 'mbind'

rts/posix/OSMem.c:739:0: error:
     error: undefined reference to 'numa_available'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSMem.c:758:0: error:
     error: undefined reference to 'numa_get_mems_allowed'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSMem.c:763:0: error:
     error: undefined reference to 'numa_bitmask_free'

rts/posix/OSMem.c:748:0: error:
     error: undefined reference to 'numa_num_configured_nodes'

rts/posix/OSThreads.c:368:0: error:
     error: undefined reference to 'numa_run_on_node'
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Failed to build exe:cardano-cli from cardano-cli-1.35.3 (which is
required by test:cardano-cli-golden from cardano-cli-1.35.3).
`

**Pull request closed without merging**
