### PR TITLE
Gufmar/deb untu setup build

### PR DESCRIPTION
**Pull request by gufmar**
- This PR **does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [x] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

### CODE REVIEW

**Comment by erikd** [comment]
@gufmar Probably best to squash that down to a single commit with a title something like "Improve build instructions". Otherwise looks good.

**Comment by erikd** [comment]
@gufmar Why close this? Just rebase and force push.

Interactive rebasing: https://stackoverflow.com/questions/5667884/how-to-squash-commits-in-git-after-they-have-been-pushed

You can then re-open this PR.

**Comment by gufmar** [comment]
Didn't know about that 
"interactive rebasing" seems doable somehow but at my knowledge level it's much easier to create [748]

**Comment by erikd** [comment]
Interactive rebasing is a skill worth learning. I use it all the time to clean up work-in-progress commit history.

**Pull request closed without merging**
