### PR TITLE
tx-generator: add capability for PlutusV2 scripts

### PR DESCRIPTION
**Pull request by mgmeier**
**NB**: This branch is rebased on `jj/update-ledger`, so it should only be merged on top of that. (_EDIT_: good to go ✅ )

This PR adds PlutusV2 capability to `bench/tx-generator` and prepares it to use the new SECP built-ins.

* ✅ -- The generator can now handle PlutusV2
* ✅ -- Flake input bump for `plutus-apps`, to include latest SECP scripts for benchmarking
* ✅ -- Script redeemers are now parametrizable in the generator, instead of hard-coded
* ✅  -- workbench integration

Additionally, workbench profiles `plutus-secp-ecdsa` and `plutus-secp-schnorr` have been defined. Those provide a benchmarking auto-loop script w/ a fitting redeemer targeted to use the respective SECP built-in.

In this PR, the cost model used is the one for protocol version 8.0 from `preview`.

### CODE REVIEW

**Review by deepfire — APPROVED** [review]
Thank you @mgmeier!

**Comment by mgmeier** [comment]
Very nice; this change enables consistently (and permamently) maintaining sets of protocol parameters and Plutus cost models. A great foundation for encoding a matrix of eras and protocol versions in workbench profiles.
Thank you Serge!

**Pull request merged**
