### PR TITLE
Remove reconfigure-hlint.sh script

### PR DESCRIPTION
**Pull request by newhoggy**
* Remove the `reconfigure-hlint.sh` work around which is no longer needed.
* Add Github Actions workflow for `hlint`
* Unfortunately I have `stylish-haskell` formatting, so there are import format changes too.

### CODE REVIEW

**Review by deepfire — CHANGES_REQUESTED** [review]
@newhoggy, I have to ask to remove all formatting changes in the `bench/` folder -- including removal of `ImportQualifiedPost`.

**Comment by newhoggy** [comment]
> I have to ask to remove all formatting changes in the bench/ folder -- including removal of ImportQualifiedPost.

This is removed now.

**Review by olgahryniuk — APPROVED** [review]

**Review by deepfire — APPROVED** [review]

**Review by Jimbo4350 — APPROVED** [review]

**Comment by jbgi** [comment]
bors merge

**Review by jbgi — APPROVED** [review]

**Comment by jbgi** [comment]
bors merge

**Comment by jbgi** [comment]
bors merge

**Comment by jbgi** [comment]
bors merge

**Pull request merged**
