### PR TITLE
Prepare changelogs for 1.28 release.

### PR DESCRIPTION
**Pull request by nc6**

### CODE REVIEW

**Review by LaurenceIO — APPROVED** [review]
Looks good to me, thanks very much Nick!

**Review by dcoutts — APPROVED** [review]

**Comment by nc6** [comment]
bors merge

**Review by newhoggy — APPROVED** [review]

**Comment by nc6** [comment]
bors retry

**Comment by nc6** [comment]
bors retry

**Comment by nc6** [comment]
bors retry

**Pull request merged**
