### PR TITLE
Updated ouroboros-network dependency

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Review by newhoggy — APPROVED** [review]

**Comment by newhoggy** [comment]
Please check this comment before merging.  https://input-output-rnd.slack.com/archives/CR599HMFX/p1653992330900849?thread_ts=1653978256.958589&cid=CR599HMFX

**Review by JaredCorduan — APPROVED** [review]
:+1:

**Comment by coot** [comment]
bors merge

**Comment by nfrisby** [comment]
I think PR #3924 supersedes this one. Not sure who would take action based on that information -- @coot and/or @Jimbo4350, maybe?

**Comment by coot** [comment]
I closed it in favour of #3924.

**Pull request closed without merging**
