### PR TITLE
Run plutus script with testnet in tests

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Review by erikd — APPROVED** [review]

**Comment by newhoggy** [comment]
Example output:

```
$ cabal test cardano-testnet
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - cardano-testnet-1.27.0 (test:cardano-testnet-tests) (ephemeral targets)
Preprocessing test suite 'cardano-testnet-tests' for cardano-testnet-1.27.0..
Building test suite 'cardano-testnet-tests' for cardano-testnet-1.27.0..
Running 1 test suites...
Test suite cardano-testnet-tests: RUNNING...
test/Spec.hs
  Spec
    Plutus: OK (26.11s)
        ✓ Plutus passed 1 test.

All 1 tests passed (26.11s)
Test suite cardano-testnet-tests: PASS
Test suite logged to:
/Users/jky/wrk/iohk/cardano-node/dist-newstyle/build/x86_64-osx/ghc-8.10.4/cardano-testnet-1.27.0/t/cardano-testnet-tests/test/cardano-testnet-1.27.0-cardano-testnet-tests.log
1 of 1 test suites (1 of 1 test cases) passed.
```

**Review by Jimbo4350 — APPROVED** [review]
This is great!! Nice work @newhoggy. We should definitely (at some point) document this for users.

**Comment by Jimbo4350** [comment]
@newhoggy I think need some sort of feedback mechanism from the script to the test to that confirms the UTxO was successfully spent.

**Comment by newhoggy** [comment]
I'll look at confirming the UTxO was spent in a subsequent PR.

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
