### PR TITLE
p2p-master update

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Review by bolt12 — APPROVED** [review]
LGTM

**Review by karknu — APPROVED** [review]
LGTM.
But this PR is a bit old. I'd prefer `c46ad6772f1534e74ebd7a3f68e73239e0af089d` update.

**Comment by coot** [comment]
It seems that c46ad6772f1534e74ebd7a3f68e73239e0af089d is not upstream.  @karknu could you push it if you have it locally?

**Comment by karknu** [comment]
I was referring to the head of p2p-master in ouroboros-network, https://github.com/input-output-hk/ouroboros-network/commit/c46ad6772f1534e74ebd7a3f68e73239e0af089d

**Pull request closed without merging**
