### PR TITLE
Configurable protocol versions

### PR DESCRIPTION
**Pull request by coot**
Issue
-----------

- Fixes https://github.com/input-output-hk/ouroboros-network/issues/1971
- Makes network protocol versions configurable: can be specified in
  configuration.yaml file.  The default option is to use all supported protocols.
- This PR **does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [x] This PR contains all the work required to resolve the linked issue.

- [x] The work contained has sufficient documentation to describe what it does and how to do it.

- [x] The work has sufficient tests and/or testing (in ouroboros-network).

- [x] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [x] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by coot** [comment]
@mrBliss if you don't mind 'aeson' dependency in `ouroboros-consensus` (and `ouroboros-consensus-byron`) I can move the orphaned `FromJSON` instances for `NodeToNodeVersion` and `NodeToClientVersion` to `ouroboros-consensus-byron`.

**Comment by mrBliss** [comment]
> @mrBliss if you don't mind 'aeson' dependency in `ouroboros-consensus` (and `ouroboros-consensus-byron`) I can move the orphaned `FromJSON` instances for `NodeToNodeVersion` and `NodeToClientVersion` to `ouroboros-consensus-byron`.

I'm not keen on doing this. Do they have to be instances here? Doesn't `aeson` provide a way to use explicit parsers (in combination which `parseJSONList`). Moreover, aren't there tons of orphans already in `cardano-node`, e.g., for tracing?

**Comment by coot** [comment]
I though so :);
> Doesn't aeson provide a way to use explicit parsers (in combination which parseJSONList). 
It seems so - the `FromJSON` instance has a default implementation for `parseJSONList`.

**Comment by coot** [comment]
stale PR, closing

**Comment by coot** [comment]
Re-openned - at some point this will be updated.

**Comment by Jimbo4350** [comment]
Spoke with @coot who agreed to close this

**Pull request closed without merging**
