### PR TITLE
Rebase onto 1.26.2 & review

### PR DESCRIPTION
**Pull request by coot**
Once accepted, we should forcefully update `p2p-master` branch.

* Rebase on top of 1.26.2
* Pull github-actions changes from the `master` branch, to make the CI happy
* Some tracing fixes; once agreed they should be squashed into the right
  commits, to keep the branch tidy.

Only handful of top commits needs a review.

- Use current `ouroboros-network/p2p-master` branch
- network tracing instances: `InboundGovernorTrace`
- Trace inbound governor counters with EKG
- ConnectionManager tracer
- Clean `Cardano.Tracing.Tracers` module
- network counters configuration

### CODE REVIEW

**Comment by karknu** [comment]
The block delay related commits should be replaced with the latest version of that pr ( #2476 ). That means that 04908b2, 2b65dde, c7147aa should be replaced with ad7c2e3 and 1c756ca.

**Comment by coot** [comment]
@karknu I rebased onto `origin/p2p-master`, does it look fine to you now?

**Review by karknu — APPROVED** [review]
LGTM.

**Comment by bolt12** [comment]
Does this needs rebasing and more cleanup & review?

**Pull request merged**
