### PR TITLE
Bump CHaP and remove `ekg-json` s-r-p

### PR DESCRIPTION
**Pull request by michaelpj**
I had to fix a few things, especially adding some constraints that should be in upstream packages. We can fix those with revisions once we get those working.

### CODE REVIEW

**Comment by michaelpj** [comment]
Got rid of the one for `ekg-forward` too.

**Comment by michaelpj** [comment]
@newhoggy maybe you could take a look?

**Review by andreabedini — APPROVED** [review]
:+1:

**Review by newhoggy — APPROVED** [review]

**Comment by michaelpj** [comment]
Oh, apparently John is not good enough despite being listed as a codeowner? I'm confused.

**Comment by michaelpj** [comment]
Um, maybe @deepfire ?

**Pull request merged**
