### PR TITLE
CAD-517 chain-sync bm with structured logging

### PR DESCRIPTION
**Pull request by CodiePP**
after PR #517 the nightly chain-sync bm is based on structured logging.
adaptations to 'analyse.sh' script was necessary.

### CODE REVIEW

**Comment by deepfire** [comment]
I think that this is more complicated than it could be -- https://github.com/input-output-hk/cardano-node/pull/550 does look simpler to me.

**Comment by CodiePP** [comment]
verified in a short run:
```
commit;64890519b31106292404a6d982cf2bf3e17f8a9e
slotfirst;"2020-02-10 20:41:59.40","TraceCopyToImmDBEvent.CopiedBlockToImmDB",0
slotlast;"2020-02-10 20:51:54.94","TraceCopyToImmDBEvent.CopiedBlockToImmDB",672927
memorylast;"2020-02-10 20:51:25.36","Mem.resident",957513728
netinlast;"2020-02-10 20:51:25.36","Net.IpExt:InOctets",3940691231
netoutlast;"2020-02-10 20:51:25.36","Net.IpExt:OutOctets",211661657
diskinlast;"2020-02-10 20:51:25.36","IO.rbytes",591906365
diskoutlast;"2020-02-10 20:51:25.36","IO.wbytes",1724644624
```

**Comment by deepfire** [comment]
https://buildkite.com/input-output-hk/cardano-node-nightly-sync/builds/33#5233931b-2320-48af-bb92-8830bfd8316f also ended up well.

**Pull request merged**
