### PR TITLE
Use traceChainSyncBlockServer instead of traceChainSyncHeaderServer

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by newhoggy** [comment]
bors merge

**Review by Jimbo4350 — APPROVED** [review]

**Review by karknu — APPROVED** [review]
LGTM

**Comment by nfrisby** [comment]
Who owns the chairman tests? Is that failure an obvious CI hiccup, or is it possible that the fix you're making here is breaking something downstream that was perhaps-unintentionally a workaround for this typo?

**Comment by newhoggy** [comment]
> Who owns the chairman tests? Is that failure an obvious CI hiccup, or is it possible that the fix you're making here is breaking something downstream that was perhaps-unintentionally a workaround for this typo?

That would be me.  I think it's likely just a flaky CI issue.  As for why it's flaky, it's been that way for many months now and the fix will need collaboration with consensus/network devs.

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
