### PR TITLE
Add PeerSelectionCounters Tracer

### PR DESCRIPTION
**Pull request by bolt12**
This PR is the sibling of this one: https://github.com/input-output-hk/ouroboros-network/pull/3031

### CODE REVIEW

**Comment by bolt12** [comment]
I'm not sure if this is the only thing I should do in order to add a new tracer

**Review by karknu — APPROVED** [review]
LGTM.
Just need a fresh ouroboros-network tag.

**Comment by bolt12** [comment]
@karknu tests failed but I don't think it is my problem

**Comment by karknu** [comment]
> @karknu tests failed but I don't think it is my problem

Agreed, please merge!

**Pull request merged**
