### PR TITLE
Reduce exposed modules in cardano-api

### PR DESCRIPTION
**Pull request by Jimbo4350**

### CODE REVIEW

**Review by newhoggy — APPROVED** [review]

**Comment by LudvikGalois** [comment]
Given that this is a breaking change for downstream users of the API, should there be a note in the changelog about it?

**Comment by Jimbo4350** [comment]
Yep definitely. I'll update the changelog.

**Review by deepfire — APPROVED** [review]

**Review by MarcFontaine — APPROVED** [review]
LGTM

**Pull request merged**
