### PR TITLE
fixed typos in comments from scripts and cardano-testnet directories

### PR DESCRIPTION
**Pull request by savaki**
fixed typos in shelley-from-scratch mkfiles.sh

### CODE REVIEW

**Comment by Jimbo4350** [comment]
@savaki Thank you for the contribution. Could you update the commit message to `fixed typos in shelley-from-scratch mkfiles.sh`

**Comment by Jimbo4350** [comment]
And now squash the commits :smile:

**Comment by savaki** [comment]
Squashed.  As long as I was fixing typos, I opted to take a larger look at the setup scripts.

**Comment by savaki** [comment]
Is there anything else you'd like me to do for this prior to merge?

**Pull request merged**
