### PR TITLE
Add reforwarding option to cardano-tracer (in support of CNSA)

### PR DESCRIPTION
**Pull request by mtullsen**
# Description

We add a new reforwarding service in cardano-tracer.  It creates a new socket in which it serves the three tracing miniprotocols.  Currently,
 - reforwards trace messages to the new socket, optionally filtering trace messages. (via the config file)
 - it does not reforward EKG to the new socket.
 - it serves the datapoint protocol, but with an empty datapoint store.

### CODE REVIEW

**Review by deepfire — APPROVED** [review]
Looks good to me!

**Comment by mtullsen** [comment]
- per discussion, remove the one datapoint.

**Review by mgmeier — APPROVED** [review]
Thank you @mtullsen

**Comment by mtullsen** [comment]
now `cardano-tracer-bench` builds!

**Comment by mgmeier** [comment]
Due to being a fork, closed in favor of #5297.

**Pull request closed without merging**
