### PR TITLE
CAD-517 update dependecy to fix missing textual log output

### PR DESCRIPTION
**Pull request by CodiePP**
this should fix the missing textual log output.

### CODE REVIEW

**Comment by oneEdoubleD** [comment]
I checked out and built commit `0940a935db7b4d86d38b00f04593104f3da2cc63` however it has not fixed the issue. 

Currently, on this commit, the log output looks like this:
```
[edward:cardano.node.ChainDB:Notice:70] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Notice:38] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Debug:70] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Debug:70] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Notice:38] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Notice:38] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Notice:38] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Debug:38] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Notice:38] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Debug:38] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Debug:5] [2020-02-10 14:47:23.36 UTC] 
[edward:cardano.node.ChainDB:Info:5] [2020-02-10 14:47:23.36 UTC] 
```

**Comment by oneEdoubleD** [comment]
I've re-tested this since @deepfire's last commit and confirmed the log output now contains the expected messages.

**Comment by CodiePP** [comment]
the relevant changes have been introduced with PR #557

**Comment by deepfire** [comment]
This is still required for the fix.

**Pull request closed without merging**
