### PR TITLE
Update cardano-ledger and ouroboros-network dependencies

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Review by JaredCorduan — APPROVED** [review]
Looks good to me

**Comment by Soupstraw** [comment]
Seems to be a duplicate of this: #4111

**Comment by newhoggy** [comment]
Sorry, didn't realise you were going to update node.

**Review by Jimbo4350 — APPROVED** [review]
This fixes the memory issue completely?

**Comment by newhoggy** [comment]
This doesn't fix the memory issue because the `create-staked` command hasn't yet switch to encode via `toEncoding`, but it's a necessary change.

**Review by MarcFontaine — APPROVED** [review]
LGTM

**Review by deepfire — APPROVED** [review]

**Pull request merged**
