### PR TITLE
Ghc 8.10.2

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by mark-stopka** [comment]
`cardano-api` build fails for me with

```
Configuring library for cardano-api-1.20.0..
Preprocessing library for cardano-api-1.20.0..
Building library for cardano-api-1.20.0..
[ 1 of 17] Compiling Cardano.Api.Protocol.Types ( src/Cardano/Api/Protocol/Types.hs, dist/build/Cardano/Api/Protocol/Types.o, dist/build/Cardano/Api/Protocol/Types.dyn_o )
[ 2 of 17] Compiling Cardano.Api.Protocol.Shelley ( src/Cardano/Api/Protocol/Shelley.hs, dist/build/Cardano/Api/Protocol/Shelley.o, dist/build/Cardano/Api/Protocol/Shelley.dyn_o )
[ 3 of 17] Compiling Cardano.Api.Protocol.Cardano ( src/Cardano/Api/Protocol/Cardano.hs, dist/build/Cardano/Api/Protocol/Cardano.o, dist/build/Cardano/Api/Protocol/Cardano.dyn_o )
[ 4 of 17] Compiling Cardano.Api.Protocol.Byron ( src/Cardano/Api/Protocol/Byron.hs, dist/build/Cardano/Api/Protocol/Byron.o, dist/build/Cardano/Api/Protocol/Byron.dyn_o )
[ 5 of 17] Compiling Cardano.Api.Shelley.Genesis ( src/Cardano/Api/Shelley/Genesis.hs, dist/build/Cardano/Api/Shelley/Genesis.o, dist/build/Cardano/Api/Shelley/Genesis.dyn_o )
[ 6 of 17] Compiling Cardano.Api.Shelley.ITN ( src/Cardano/Api/Shelley/ITN.hs, dist/build/Cardano/Api/Shelley/ITN.o, dist/build/Cardano/Api/Shelley/ITN.dyn_o )
[ 7 of 17] Compiling Cardano.Api.TextView ( src/Cardano/Api/TextView.hs, dist/build/Cardano/Api/TextView.o, dist/build/Cardano/Api/TextView.dyn_o )
[ 8 of 17] Compiling Cardano.Api.TxSubmit.ErrorRender ( src/Cardano/Api/TxSubmit/ErrorRender.hs, dist/build/Cardano/Api/TxSubmit/ErrorRender.o, dist/build/Cardano/Api/TxSubmit/ErrorRender.dyn_o )
[ 9 of 17] Compiling Cardano.Api.TxSubmit.Types ( src/Cardano/Api/TxSubmit/Types.hs, dist/build/Cardano/Api/TxSubmit/Types.o, dist/build/Cardano/Api/TxSubmit/Types.dyn_o )
[10 of 17] Compiling Cardano.Api.Typed ( src/Cardano/Api/Typed.hs, dist/build/Cardano/Api/Typed.o, dist/build/Cardano/Api/Typed.dyn_o )
[11 of 17] Compiling Cardano.Api.TxSubmit ( src/Cardano/Api/TxSubmit.hs, dist/build/Cardano/Api/TxSubmit.o, dist/build/Cardano/Api/TxSubmit.dyn_o )

src/Cardano/Api/TxSubmit.hs:29:1: error: [-Wunused-imports, -Werror=unused-imports]
    The import of `StandardShelley'
    from module `Ouroboros.Consensus.Shelley.Protocol.Crypto' is redundant
   |
29 | import           Ouroboros.Consensus.Shelley.Protocol.Crypto (StandardCrypto, StandardShelley)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build cardano-api-1.20.0 (which is required by
exe:cardano-cli from cardano-cli-1.20.0). See the build log above for details.
```

when using this on top of master as a cherry-picked commit...

**Comment by newhoggy** [comment]
> `cardano-api` build fails for me with
> 
> ```
> Configuring library for cardano-api-1.20.0..
> Preprocessing library for cardano-api-1.20.0..
> Building library for cardano-api-1.20.0..
> [ 1 of 17] Compiling Cardano.Api.Protocol.Types ( src/Cardano/Api/Protocol/Types.hs, dist/build/Cardano/Api/Protocol/Types.o, dist/build/Cardano/Api/Protocol/Types.dyn_o )
> [ 2 of 17] Compiling Cardano.Api.Protocol.Shelley ( src/Cardano/Api/Protocol/Shelley.hs, dist/build/Cardano/Api/Protocol/Shelley.o, dist/build/Cardano/Api/Protocol/Shelley.dyn_o )
> [ 3 of 17] Compiling Cardano.Api.Protocol.Cardano ( src/Cardano/Api/Protocol/Cardano.hs, dist/build/Cardano/Api/Protocol/Cardano.o, dist/build/Cardano/Api/Protocol/Cardano.dyn_o )
> [ 4 of 17] Compiling Cardano.Api.Protocol.Byron ( src/Cardano/Api/Protocol/Byron.hs, dist/build/Cardano/Api/Protocol/Byron.o, dist/build/Cardano/Api/Protocol/Byron.dyn_o )
> [ 5 of 17] Compiling Cardano.Api.Shelley.Genesis ( src/Cardano/Api/Shelley/Genesis.hs, dist/build/Cardano/Api/Shelley/Genesis.o, dist/build/Cardano/Api/Shelley/Genesis.dyn_o )
> [ 6 of 17] Compiling Cardano.Api.Shelley.ITN ( src/Cardano/Api/Shelley/ITN.hs, dist/build/Cardano/Api/Shelley/ITN.o, dist/build/Cardano/Api/Shelley/ITN.dyn_o )
> [ 7 of 17] Compiling Cardano.Api.TextView ( src/Cardano/Api/TextView.hs, dist/build/Cardano/Api/TextView.o, dist/build/Cardano/Api/TextView.dyn_o )
> [ 8 of 17] Compiling Cardano.Api.TxSubmit.ErrorRender ( src/Cardano/Api/TxSubmit/ErrorRender.hs, dist/build/Cardano/Api/TxSubmit/ErrorRender.o, dist/build/Cardano/Api/TxSubmit/ErrorRender.dyn_o )
> [ 9 of 17] Compiling Cardano.Api.TxSubmit.Types ( src/Cardano/Api/TxSubmit/Types.hs, dist/build/Cardano/Api/TxSubmit/Types.o, dist/build/Cardano/Api/TxSubmit/Types.dyn_o )
> [10 of 17] Compiling Cardano.Api.Typed ( src/Cardano/Api/Typed.hs, dist/build/Cardano/Api/Typed.o, dist/build/Cardano/Api/Typed.dyn_o )
> [11 of 17] Compiling Cardano.Api.TxSubmit ( src/Cardano/Api/TxSubmit.hs, dist/build/Cardano/Api/TxSubmit.o, dist/build/Cardano/Api/TxSubmit.dyn_o )
> 
> src/Cardano/Api/TxSubmit.hs:29:1: error: [-Wunused-imports, -Werror=unused-imports]
>     The import of `StandardShelley'
>     from module `Ouroboros.Consensus.Shelley.Protocol.Crypto' is redundant
>    |
> 29 | import           Ouroboros.Consensus.Shelley.Protocol.Crypto (StandardCrypto, StandardShelley)
>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> cabal: Failed to build cardano-api-1.20.0 (which is required by
> exe:cardano-cli from cardano-cli-1.20.0). See the build log above for details.
> ```
> 
> when using this on top of master as a cherry-picked commit...

This is because `ghc-8.10.2` is comparably more strict and it is easy for new code to creep in (past our CI that currently only checks `ghc-8.6.5`) that won't compile on the new compiler.

**Comment by erikd** [comment]
We need 8.10.2 in CI.

**Comment by mark-stopka** [comment]
> We need 8.10.2 in CI.

If you were using GitHub actions I already added the support :-) maybe @tiredpixel is a NixOS guy...

:-) I am adding it at least to my Docker CI process...

**Comment by newhoggy** [comment]
I think maybe it's fixed now.  Just waiting for CI.

**Comment by mark-stopka** [comment]
I can confirm my build is fine on `x86_64` platform using [following image](https://github.com/2nd-Layer/docker-hub-cardano-images/tree/59b7672f3c188786d984b31a7943f25a7b90231a/cardano-node/latest), I will test other platforms during the next week.

**Comment by hasufell** [comment]
What's the status of this @newhoggy ?

**Comment by mrBliss** [comment]
@hasufell #1990 was merged a few hours ago.

**Pull request closed without merging**
