### PR TITLE
All The Jobs!

### PR DESCRIPTION
**Pull request by angerman**
Build
- [x] windows cross compiled libraries
- [x] re-enable the darwin builds for inspection.

### CODE REVIEW

**Comment by angerman** [comment]
I'm reasonably confident this commit is correct, however the underlying libraries (cardano-node) just don't build.

**Comment by 365andreas** [comment]
> Looks hacky, but it builds.
> Is this just disabling the LiveView on Windows or?

Now using `--live-view` on Windows will just do nothing (`return ())

I will change it so that using `--live-view` will just spawn a simple node without the TUI.

**Pull request merged**
