### PR TITLE
Call validateTxMetadata on transaction metadata parsed from JSON

### PR DESCRIPTION
**Pull request by intricate**
At this time, `jsonToMetadata` already performs the appropriate validation on the transaction metadata during its JSON parsing. However, it still might make sense to call `validateTxMetadata` just in case more validation rules that aren't covered by `jsonToMetadata` are added in the future.

### CODE REVIEW

**Review by rvl — APPROVED** [review]
Good idea

**Comment by rvl** [comment]
Sorry my review wasn't sufficient.

Bors-ng just requires single review approval (`bors.toml` sets `required_approvals=1`).
This GitHub repo has master branch protection with codeowner approvals enabled.

When bors-ng tried to push the merge commit to github it was rejected.

Rather than handling the error and sending a comment to the PR, bors-ng does the erlang thing and crashes.

The error message is visible by checking the :x: status from bors in the merge commit.

**Review by newhoggy — APPROVED** [review]

**Pull request merged**
