### PR TITLE
[GH-334] Checking for CI node failure.

### PR DESCRIPTION
**Pull request by ksaric**
Checking if this fixes the chairman CI - https://github.com/input-output-hk/cardano-node/pull/348

### CODE REVIEW

**Comment by ksaric** [comment]
@mrBliss Ah, you wrote faster here than I could in Slack. 
I understood, the PR is not for merging, just seeing if this is what might have cause the issue.

**Comment by ksaric** [comment]
Well, that didn't help - https://hydra.iohk.io/build/1429704

**Comment by ksaric** [comment]
Rewrote history, second attempt.

**Comment by ksaric** [comment]
Mystery resolved.

**Comment by dcoutts** [comment]
The code change looks fine, but I don't understand how it is related to #348. 

The failure I see in the logs of #348 is:
```
cardano-node: user error ((line 1, column 1):
unexpected end of input
expecting white space or JSON value)
```
I don't understand how that error is related to the change in this PR.

**Pull request merged**
