### PR TITLE
LiveView: stop the TUI & node itself.

### PR DESCRIPTION
**Pull request by denisshevchenko**
Now pressing `q` (in a live view) stops the TUI as well as the node itself.

### CODE REVIEW

**Comment by denisshevchenko** [comment]
So, my idea is to make `q` more powerful. We display:

> Press Q to quit

and user expects that `quit` means complete exit (stop the node). So we pass `nodeThread` to `LiveView`, and after user pressed `q` - just `cancel` node's working thread (function `handleSimpleNode`).

**Comment by ksaric** [comment]
That is fine, but we need it to work for other signals as well.
We cannot have a terminal that doesn't respond to outside signals.

One of these signals is CTRL+C and it's currently being swallowed by that same thread (I presume).
You can simply rethrow the exception or throw an asynchronous one.

**Pull request merged**
