### PR TITLE
fixes LiveView memory display

### PR DESCRIPTION
**Pull request by CodiePP**
minimal change to reenable display of memory on Linux and Mac OSX in LiveView/TUI

### CODE REVIEW

**Comment by mark-stopka** [comment]
I was worried this did not fix the issue properly as the bar was most of the time at full, however now I see there was some memory usage spike and it fell back to less than 100% of the maximum, so I can confirm that this works when cherry-picked into 1.18.0 release...

image

**Comment by intricate** [comment]
Thanks @mark-stopka

**Comment by bergr01** [comment]
@intricate @CodiePP Are those "checkForUnexpectedThunks ["Meresident LiveViewBackend"] lvs" correct or do they need adjusting too?

**Pull request merged**
