### PR TITLE
submit-api: add tx_submit_fail_count metric

### LINKED ISSUE #3233: [FR] - cardano-submit-api add failed transaction metric
*External* 

**Area**
*Other*  cardano-submit-api

**Describe the feature you'd like**
Right now, the `cardano-submit-api` report only the `tx_submit_count` metric. It would be truly awesome if could also count failed transactions.

### PR DESCRIPTION
**Pull request by sorki**
Similar to `tx_submit_count` for failed submissions.

Closes #3233.

### CODE REVIEW

**Comment by mmahut** [comment]
Tested, works as expected!

**Comment by reqlez** [comment]
I guess I was not the only crazy person who thinks this metric is mandatory.

**Comment by Jimbo4350** [comment]
I've asked @newhoggy to review this PR

**Review by newhoggy — APPROVED** [review]

**Comment by newhoggy** [comment]
Thanks for the PR!

**Pull request merged**
