### PR TITLE
Document how to disable ledger peers

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Review by disassembler — APPROVED** [review]

**Review by newhoggy — APPROVED** [review]

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Review by olgahryniuk — APPROVED** [review]

**Comment by coot** [comment]
bors merge

**Pull request merged**
