### PR TITLE
Print tx fee when using transaction build command

### LINKED ISSUE #3024: [FR] - return the transaction fee when executing `transaction build` command
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
When the `transaction build` command is executed, the transactions is balanced and validated so we know the tx fee. For better transparency, it would be useful that the `transaction build` to return the transaction fee.

**Describe alternatives you've considered**
in order to find the tx fee, we need to do some math at this moment.

**Additional context / screenshots**

### PR DESCRIPTION
**Pull request by Jimbo4350**
Resolves #3024

### CODE REVIEW

**Review by dcoutts — APPROVED** [review]
LGTM, but don't add more detail than this. Extra detail can go into `cardano-cli transaction view`. The only reason this info here fits ok is because it's only here that we really know which output is the change. We should not add more misc ad-hoc things to a single command that is for building, not viewing transactions.

**Comment by Jimbo4350** [comment]
> LGTM, but don't add more detail than this. Extra detail can go into `cardano-cli transaction view`. The only reason this info here fits ok is because it's only here that we really know which output is the change. We should not add more misc ad-hoc things to a single command that is for building, not viewing transactions.

I was thinking of adding a `--verbose` flag that defaults to not printing the fee.

**Review by newhoggy — APPROVED** [review]

**Pull request merged**
