### PR TITLE
workbench & analysis: assorted fixes

### PR DESCRIPTION
**Pull request by deepfire**
- locli:
   - report schema improvements for data publishing
   - beginning of sectioning in reports
   - generalise and increase reliability of report templates
   - various progress & error reporting enhancements
   - conditional decoding error tolerance
   - fixes: slot gap detection, legacy chainsync decoding, 
   - FS & Net IO metrics
- workbench:
   - partial JSON compactification for human readability
   - make `tx-generator.service` respect the `runScriptFile` option
   - partial fix for the message frequency analyser
   - RTS mode & verbosity control
   - fixes: inlne filter expressions, cabal prebuild
   - ad-hoc sets, local & remote

### CODE REVIEW

**Review by fmaste — APPROVED** [review]

**Review by Jimbo4350 — DISMISSED** [review]
Again, please squash the commits. This is polluting the git history of cardano-node.

**Review by mgmeier — APPROVED** [review]

**Review by Jimbo4350 — APPROVED** [review]

**Pull request merged**
