### PR TITLE
Wire up optional datums cli

### LINKED ISSUE #2919: [FR] - Add support for optional datums
**Internal/External**
*Internal*   if an IOHK staff member.

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Describe the feature you'd like**
Looking at the [formal spec](https://hydra.iohk.io/build/6752480/download/1/alonzo-changes.pdf) we know that "optional datum objects can be added to the datum map for the purpose of posting them on chain for communication", and Figure 3 on page 10 defines all datum objects are stored in the same DataHash->Datum map. We require support for providing these optional datums using cardano-cli.

**Describe alternatives you've considered**
None

**Additional context / screenshots**
None

### PR DESCRIPTION
**Pull request by Jimbo4350**
Resolves #2919

### CODE REVIEW

**Review by newhoggy — APPROVED** [review]

**Comment by newhoggy** [comment]
Just one thing.  I'm curious about the distinction between optional datum and extra script data.

**Comment by Jimbo4350** [comment]
>Just one thing. I'm curious about the distinction between "optional datum" and "extra script data" which appear to be different names from the same thing.

Duncan uses the term extra script data. I'll remove all references to optional datum.

**Comment by james-iohk** [comment]
> Duncan uses the term extra script data. I'll remove all references to optional datum.

FYI, "optional datum" is used throughout the "Ledger integrating Plutus Core" spec and it is how it is known in the community so far. Just wanted to share, do what you think's best :)

**Comment by WhatisRT** [comment]
Extra script data sounds weird, I've never heard this name being used. I think pretty much all the ledger folks (and Polina/me) call it optional datum(s) or optional datum objects. Script data seems like an accident that snuck in somewhere.

**Comment by dcoutts** [comment]
This is my mistake. I should have deleted the extra data once we finished annotating the witnesses and txou data into the tx body.

We can delete `txExtraScriptData` in the `TxBodyContent`.

**Comment by dcoutts** [comment]
Confusion resolved: the actual changes we want are in this old PR branch which needs rebasing and committing.
https://github.com/input-output-hk/cardano-node/commits/dcoutts/api-cli-txout-datums

**Comment by Jimbo4350** [comment]
I wasn't aware that the ledger team had changed their mind re: where the optional datums will be stored

**Pull request closed without merging**
