### PR TITLE
CAD-2658 Fix script file option name

### PR DESCRIPTION
**Pull request by newhoggy**
Rename `--script-file` to `--payment-script-file`.

### CODE REVIEW

**Comment by newhoggy** [comment]
A subsequent PR will introduce `--stake-script-file`.

**Review by erikd — APPROVED** [review]

**Comment by newhoggy** [comment]
bors merge

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
Edited: We should hide hide with old arg (`script-file`) for backwards compatibility.

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
See above comment

**Comment by newhoggy** [comment]
Closing to combine with https://github.com/input-output-hk/cardano-node/pull/2587

**Pull request closed without merging**
