### PR TITLE
tx-generator cleanups

### PR DESCRIPTION
**Pull request by MarcFontaine**
* Replace `IO` with `Monad m => m` in some types.
* reintroduce `ToUTxOList`.
* Remove legacy tx-set based `FundSet`. (Use `type FundSet = [ Fund ]` for now.)

### CODE REVIEW

**Review by mgmeier — APPROVED** [review]

**Comment by MarcFontaine** [comment]
ToDo:
Fix this: With ix-sets removed there needs to be a way to split funds and reuse the change.
(that is : a splitting transaction with two target wallets).

**Pull request merged**
