### PR TITLE
Remove Mark Stopka contributions

### PR DESCRIPTION
**Pull request by mark-stopka**
Issue
-----------

- After recent disputes with the Cardano community I request you to remove all my contributions towards `cardano-node` code as I have not signed physically or virtually any contributor agreement that would transfer intellectual property rights to any 3rd party and as per Act No. 121/2000 any such property right transfer needs to be explicit.

- This PR **does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [X] This PR contains all the work required to resolve the linked issue.

- [X] The work contained has sufficient documentation to describe what it does and how to do it.

- [ ] The work has sufficient tests and/or testing.

- [X] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [ ] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by erikd** [comment]
May I ask for a link to these disputes?

**Comment by mark-stopka** [comment]
Good evening @erikd,
long story short @CharlesHoskinson yesterday announced that the long awaited Hydra paper will be published to [AICR ePrint](https://eprint.iacr.org/); as I were after that paper some time ago, I've remembered the initial due-date for the paper finalization was in October, [so I poked a bit with a Twitter comment](https://twitter.com/PERLUR_Mark/status/1236319879017439233) after which I was called toxic, which as a grown-up I can comfortably take. Some s**t storm continued, but the bottom line is...

I [replied to CH that if I am toxic, then he is a snake-oil salesman](https://twitter.com/PERLUR_Mark/status/1236543516693663744) after which he blocked me, which I could not care less about, however the next morning I woke up to being blocked on all Cardano Telegram channels and /r/cardano sub-reddit, thus I no longer feel like I can be a valuable contributor to this project and active member of the community as the communications channels available to me are severely limited.

There has been some discussion regarding the status today which I was unable to take part of today (as I am banned on the respective Telegram channel), however I do not believe I have sufficient community support to feel comfortable to contribute to this project and the avenue I will be exploring will be genesis re-structuring and forking the code-base while most probably actively contributing [towards Tezos](https://github.com/input-output-hk/decentralized-software-updates/issues/91).

This situation may resolve itself as I was invited to talk about the situation and current state of the ecosystem by one of the respective YouTubers, but I am more skeptical than him as I see it as a high risk to waste time and effort on a project our of which I may be eventually forced out.

**Comment by erikd** [comment]
I have escalated this internally at IOHK.

**Comment by dcoutts** [comment]
@mark-stopka as you know, I don't engage much on the community channels (I'm kind of busy!), so I'm not personally aware of the details here, but I understand it's been a bit of a flame-fest over a period of time. I should say that from the little of Reddit that I've followed in recent months, you have stood out as someone who actually reads and understands, rather than being uncritically positive. The fact that you clearly read the specifications and make contributions like the docker images has certainly been noticed by the engineering team.

My own advice would be to take a moment to reflect. You can be right without getting into conflict with folks. You can speak truth to power (e.g. about overly simplistic positive public messaging) without coming across as a troll. Have a look at the code of conduct stuff, even if you don't completely agree with it. We want to be right, and get along with each other.

As for Hydra, I have been peripherally involved and I can assure you it took as long as it did simply because that's how long it took! Everyone would have liked it to be ready sooner. I hope you enjoy the bits about timing accurate simulations.

**Comment by mark-stopka** [comment]
@dcoutts seems to me we reached an impasse, thus I will follow advice given by @vincenthz, and build my own blockchain since asking questions on Telegram is clearly against the code of conduct (@dcoutts thank you for actually providing a valuable input on the slot assignment overlap on Reddit, Vincent was not as helpful). I think our team will enjoy your high quality codebase, although we wait for release of Voltaire for an actual fork and genesis reset (see DUNE Network Tezos fork model).

Now please merge this PR and let's move on with our lives.

**Comment by vincenthz** [comment]
@mark-stopka not sure why do you think that was an "advice", merely that I wasn't willing to discuss further on the topic with you since, despite my efforts to correct your misunderstandings about the slots, you stubbornly disagreed and argumented in a rude way; since you obviously know better, I wish you all the best.

**Comment by mark-stopka** [comment]
@vincenthz just for reference, these were the exact words said:

@vincenthz: why don't you start write own blockchain 
@mark-stopka: why don't you rather shutup when you have nothing of value to add

Only think here I did wrong in my humble opinion was not to use more politically correct "keep quiet".

I answer you why, because building on other's people ideas is the spirit of open-source and the bazaar approach, you guys enjoy your cathedral.

- [The Cathedral and the Bazaar
](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar)

**Comment by mark-stopka** [comment]
Request must be resolved by Wednesday, April 7, 2020  - within 30 days since submission as per Supreme Administrative Court of the Czech Republic rulling [2 Afs 79/2015 - 36
](https://iudictum.cz/27749/2-afs-79-2015-36).

**Comment by mark-stopka** [comment]
@dcoutts I was going thru your reply once again, and I think you could track those collisions using separate `poldercast` message type, have the next pool publish notification of allowed collision, have the proof either embeded in one of the following blocks within an epoch and then calculate the rewards and split on slot battles evenly among participants.

If the zero-knowledge proof is infeasible then nodes could vote on an `event announcement`, having such a dynamic properties. Including possibility to have variable `k` and `a0` would also be very useful for both adaptive security and self-governance.

**Comment by dcoutts** [comment]
@mark-stopka We do not wish to part on bad terms, so we will accept your request to remove your contributions [*]. I'm genuinely sorry you feel it had to come to this. As I said before, it's clear you have a good grasp of the project and have much to contribute. I hope we can cooperate in future.

> I was going thru your reply once again, and I think you could track those collisions using separate poldercast message type, have the next pool publish notification of allowed collision, have the proof either embeded in one of the following blocks within an epoch and then calculate the rewards and split on slot battles evenly among participants.

Consider what Praos looks like as the slot size tends towards zero, while keeping the same average time between blocks. This means there are in practice no exact collisions in a single slot, but there are still blocks that occur so close to each other that there is not enough time for a block to get from one to the other.

Remember also that we do not wish to publish in advance that we are going to create a block, because the whole point of the Praos private slot leader schedule is to improve security by making it harder to attack the next slot leader, since you don't know who they are going to be.

For your intuition that both slot leaders could get the rewards, consider the input endorsers from the original Ouroboros paper. In a linear block chain it's tricky to have multiple concurrent leaders, but there's no such problem for input endorsers.

[*] Note that we do not accept that we are required to remove your contributions (consider something like the Linux kernel where contributors merely publish derived works under the project license).

**Comment by mark-stopka** [comment]
> As I said before, it's clear you have a good grasp of the project and have much to contribute. I hope we can cooperate in future.

I hope so too. As per the rest goes, I have my opinion on how to make the project more open to outside collaborators and the idea is to have a Independent Subject Matter Experts committee that will have NDA protected, privileged access to work in progress research similarly to [input-output-hk/decentralized-software-updates](https://github.com/input-output-hk/decentralized-software-updates), but I believe there it's open due to legal requirements of the grant that had been provided by the EU. I briefly touched the topic on [Digital Fortress YouTube Channel](https://www.youtube.com/channel/UCUbDk_ANFGeQBn3829u7KDA) where we discuss the situation with Rick, the upload should be there by morning UK time.

> consider something like the Linux kernel where contributors merely publish derived works under the project license

I don't know how many mainline patches you contributed to Linux mainline kernel, however let me tell you that each mainline contributor is [required to sign Developer Certificate of Origin](https://developercertificate.org/) which in it's part involves

> (d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

License law is a complex and in no way internationally harmonized which is why large scale OSS projects adopt some sort of Contributor Agreements. There are even small projects that grew larger and had to track down each contributor and have it signed retrospectively due to legal compliance reasons as it was raised as a risk in a legal due-diligence in M&A transactions.

I wish you guys luck delivering to the mainnet, and hopefully changes will make outside contributors more comfortable with not only the developer interactions and code contributions, but also with regards to entire community engagement.

Effectively it's little moronic to be building censorship resistant, decentralized blockchain solution whilst engaging in active censorship across several media channels because someones ego got hurt for his inability to deliver on time repeatedly which he is unable to accept and own to the full extend of it's impact on other members of the ecosystem.

You also weren't present at the Bulgaria event where things of this sort have been discussed in person, changes has been proposed, accepted, but effectively not implemented. Anyone willing to open their eyes can see growing conflict of interest between IOHK, CF and EMURGO.

Looking at some PRs it's obvious that some delivery scope has been legally committed as those PRs contain clear bill of delivery with a checklist, but the secrecy around what is an actual contracted scope is mind boggling. I have asked if there is a SoW between IOHK and a CF, and I was told by your co-founder and CF treasurer that they think there is, and I was also promised to be given access to the scope definition. That was September 2019, last think I remember regarding this was CH going on YouTube about how that ain't happening.

If you don't think it's important for people who want to build below, inside, on top and around the Cardano Blockchain project to actually know what's within a scope of IOHK deliveries and where are their opportunities to contribute and add value, then I don't think this can ever become truly open project with several independent contributing parties as that would lead to inefficiencies in deliveries which would make it uneconomical.

Scope needs to be formally defined, interfaces between components need to be specified prior to implementation so that parallel development streams by 3rd party contributors are possible. Now more than ever, when the project governance part relies heavily on people in conflict of interest.

**Comment by erikd** [comment]
IANAL but I do not think contributor agreements are necesasry. Github has [Terms Of Service](https://help.github.com/en/github/site-policy/github-terms-of-service#6-contributions-under-repository-license) that covers this. Specifically

> Whenever you make a contribution to a repository containing notice of a license, you license your contribution under the same terms, and you agree that you have the right to license your contribution under those terms.

**Comment by mark-stopka** [comment]
@erikd I don't think one needs to be a lawyer to understand that ratified international treaties supersede most constitutional laws (I remember only US being the exception from my studies of international trade at Institute of Law and Legal Science in Prague), federal laws supersede national laws, national laws supersede local ordinances and all of the prior supersede civil contracts such as terms of service.

The ultimate issue here would be that Czech Copyright Act explicitly prohibits waiver of copyright rights; you can of course grant a license, however it's again prohibited to grant such license for indefinite period of time and waive a right to recall such granted license.

Czech Republic is an international R&D hub for RedHat and SUSE, trust me, they have a lot of headache around this since the respective amendment was passed in 2015.

Of course in this case it would legally go so, that the case would be litigated in Czech court where I would most probably win, and then with the final judgment another litigation would have to take place in either general courts of Hong Kong or under Rules of Arbitration of the International Chamber of Commerce in Hong Kong where I would have to demand an enforcement of the judgement from different jurisdiction which could go in any direction.

But of course we won't find out what the outcome would be and nobody want's to go to litigation for 3 commits.

**Comment by matiwinnetou** [comment]
@mark-stopka your so smart and knowledgable about software but on the human nature - you are totally weird. When I read it all it feels that your genuine brilliance causes you some interpersonal issues (IMHO).

**Comment by mark-stopka** [comment]
> @mark-stopka your so smart and knowledgable about software but on the human nature - you are totally weird. When I read it all it feels that your genuine brilliance causes you some interpersonal issues (IMHO).

Sure, I am [the one with the issue](https://twitter.com/bennd77/status/1271833067687116800)... 😭  

(And then one wonders why would someone look-up and comment on a 3 month old, already closed PR on GitHub...) 🤷

PS: Appreciate the emojis, I had to google them as I am temporarily on a non-standard platform where I don't know how to make them on the keyboard 😂

**Pull request merged**
