### PR TITLE
Fix missing trace-forward messages

### PR DESCRIPTION
**Pull request by jutaro**
Fix the bug and add a test case.

### CODE REVIEW

**Review by deepfire — APPROVED** [review]

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
@jutaro squash the commit history please. There are unnecessarily small commits.

**Review by Jimbo4350 — APPROVED** [review]

**Review by olgahryniuk — APPROVED** [review]

**Review by deepfire — APPROVED** [review]

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
I do not appreciate that I approved this PR on the condition that the commits were squashed. There are now 24 commits on this PR and you are trying to merge it @deepfire . Please squash the commits

**Pull request merged**
