### PR TITLE
Nix fixes - 1.35

### PR DESCRIPTION
**Pull request by jbgi**
this is a backport of #4748.

### CODE REVIEW

**Comment by jbgi** [comment]
bors try

**Comment by jbgi** [comment]
bors try

**Comment by jbgi** [comment]
bors try

**Comment by jbgi** [comment]
bors try-

**Comment by jbgi** [comment]
bors try

**Comment by jbgi** [comment]
bors try

**Comment by disassembler** [comment]
boors r-

**Review by JaredCorduan — APPROVED** [review]

**Comment by jbgi** [comment]
bors retry

**Comment by jbgi** [comment]
bors retry

**Pull request merged**
