### PR TITLE
Calculate minimum ADA value

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by newhoggy** [comment]
This code is from `cardano-wallet` and needs a lot of cleanup.

**Comment by newhoggy** [comment]
Example:

```
$ cardano-cli transaction calculate-min-value --multi-asset "5 00000000000000000000000000000000000000000000000000000000.couttscoin + 6 00000000000000000000000000000000000000000000000000000001.jimbocoin" --protocol-params-file params.json
Result Lovelace 1703702
```

**Comment by newhoggy** [comment]
Fixes https://github.com/input-output-hk/cardano-node/issues/2571

**Review by erikd — APPROVED** [review]

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
bors merge

**Comment by newhoggy** [comment]
This adds a new command that calculates the "minimum ADA value" (sometimes known as the minimum deposit): https://developers.cardano.org/en/development-environments/native-tokens/multi-asset-tokens-explainer/#:~:text=Ada%20is%20Cardano's%20principal%20currency,currently%20set%20at%201%20ada).

**Pull request merged**
