### PR TITLE
Update cardano-node-cli-reference.md

### PR DESCRIPTION
**Pull request by nahern**
updating commands with era flags and removing redundant commands and removing Shelley appends.

### CODE REVIEW

**Review by Jimbo4350 — COMMENTED** [review]
LGTM just a couple of changes

**Review by nahern — COMMENTED** [review]
updated with comments from Jordan.

**Review by nahern — COMMENTED** [review]
typo fix

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
LGTM!

**Review by Jimbo4350 — APPROVED** [review]
LGTM!

**Comment by Jimbo4350** [comment]
subsumed by: https://github.com/input-output-hk/cardano-node/pull/2442

**Pull request closed without merging**
