### PR TITLE
Trace changes

### LINKED ISSUE #4560: [FR] - The new tracing system does not use severities for `StartupTracer`
[`const Notice`](https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Node/Tracing/Tracers.hs?plain=1#L142) is used while we ought to have a proper severities like the old logging system does [here](https://github.com/input-output-hk/cardano-node/blob/master/cardano-node/src/Cardano/Tracing/Startup.hs?plain=1#L27-L34).

### PR DESCRIPTION
**Pull request by coot**
This PR contains various small changes to traces.

- Removed kind field from NodeTo{Node,Client}VersionData
- Fixed a typo
- Changed IP ToJSON instance
- Simplified ToJSON instance of LocalRootPeers
- Use Notice severity for NetworkConfigUpdate
- Added severityStartupTracer

Fixes #4560

### CODE REVIEW

**Review by Jimbo4350 — CHANGES_REQUESTED** [review]
6 commits is overkill for these changes. Please squash the commits to a single commit.

**Review by jutaro — APPROVED** [review]
Looks good

**Comment by coot** [comment]
@Jimbo4350 I squashed all the commits.

**Review by Jimbo4350 — APPROVED** [review]

**Pull request merged**
