### PR TITLE
Remove testnet subdir

### PR DESCRIPTION
**Pull request by MarcFontaine**
Move the modules from `testnet` to `src`.

### CODE REVIEW

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/cardano-node/issues/4558

**Comment by MarcFontaine** [comment]
merge after: https://github.com/input-output-hk/cardano-node/pull/4544

**Comment by Jimbo4350** [comment]
So now I would do the following:
- `cardano-testnet/src/Testnet/Commands` -> `cardano-testnet/src/Parsers`
- `cardano-testnet/src/Testnet/{Babbage,Byron,Cardano,Shelley}.hs` should remain where they are and the test moved to the `src` dir

**Review by Jimbo4350 — APPROVED** [review]
LGTM just a couple other things

**Pull request merged**
