### PR TITLE
CAD-792:  bump monitoring for non-API-breaking efficiency improvements

### PR DESCRIPTION
**Pull request by deepfire**
1. The new `iohk-monitoring` preserves more laziness, see: https://github.com/input-output-hk/iohk-monitoring-framework/pull/550
   - The performance impact is described in CAD-792 -- roughly a 10% reduction in wallclock for a locally-served chainsync benchmark.

1. Some minor API sync.
1. More improvements coming soon in a subsequent PR.. API breaking, though.

#### TODO
- [x] merge https://github.com/input-output-hk/iohk-monitoring-framework/pull/550

- This PR **does not result** in breaking changes to upstream dependencies.

Checklist
---------
- [ ] This PR contains all the work required to resolve the linked issue.

- [ ] The work contained has sufficient documentation to describe what it does and how to do it.

- [x] The work has sufficient tests and/or testing.

- [x] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [x] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by dcoutts** [comment]
Nice. So this PR will need to wait for that PR to be merged to `iohk-monitoring-framework`'s master branch.

**Comment by deepfire** [comment]
> So this PR will need to wait for that PR to be merged to iohk-monitoring-framework's master branch.

Yes, sorry, should have made this a draft PR.

**Comment by deepfire** [comment]
bors merge

**Comment by deepfire** [comment]
bors merge

Had to push a fix for the CI failure -- the changes in strictness exposed a latent bug fixed by the last commit:

- https://hydra.iohk.io/eval/893806
- https://iohk-nix-cache.s3-eu-central-1.amazonaws.com/log/z5q5rxn8fmr4sflcbb9jjjl6m91w25fq-vm-test-run-chairmans-cluster-test.drv

**Pull request merged**
