### PR TITLE
Enrich the Ledger replay tracers and inbound-governor tracer & metrics.

### PR DESCRIPTION
**Pull request by Jasagredo**

### CODE REVIEW

**Review by dnadales — APPROVED** [review]

**Review by Jasagredo — COMMENTED** [review]
I cannot approve my own PR but it looks good to me after your changes @coot

**Review by coot — APPROVED** [review]

**Review by EncodePanda — APPROVED** [review]
all good on events side

**Comment by coot** [comment]
bors merge

**Review by nc6 — APPROVED** [review]

**Review by MarcFontaine — APPROVED** [review]
LGTM

**Comment by nc6** [comment]
bors merge

**Pull request merged**
