### PR TITLE
Update cardano-ledger-specs

### PR DESCRIPTION
**Pull request by newhoggy**
* Pushed the `cardano-ledger-specs` and `ouroboros-network` dependencies as far forward as I can without compile errors
* Code changes for https://github.com/input-output-hk/ouroboros-network/pull/2896

### CODE REVIEW

**Review by coot — APPROVED** [review]
LGTM

**Review by Jimbo4350 — APPROVED** [review]
LGTM! Can we squash the commits?

**Comment by newhoggy** [comment]
Squashed

**Comment by newhoggy** [comment]
bors merge

**Pull request merged**
