### PR TITLE
Export TxBodyScriptData from Cardano.Api

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
For now I need this for a work around for #2936, but it seems useful to export this in any case.

### CODE REVIEW

**Comment by sjoerdvisscher** [comment]
The build seems to have succeeded but it is not picked up by Github?

**Review by rvl — APPROVED** [review]
I like it, but this needs a codeowner approval to be merged.

**Review by newhoggy — APPROVED** [review]

**Comment by sjoerdvisscher** [comment]
@newhoggy @rvl Thanks for the approvals! Could one of you merge it too? I can't because the CI failed to finish, even though all tests succeeded.

**Comment by rvl** [comment]
It seems like both Buildkite and Hydra CI finished, but were unable to post status to the GitHub API.

bors merge

**Pull request merged**
