### PR TITLE
Remove typo in cardano-node-cli-reference.md

### PR DESCRIPTION
**Pull request by MaxKless**
I removed a single "This" that seems like the abandoned start of a sentence.

### CODE REVIEW

**Comment by Jimbo4350** [comment]
Thanks @MaxKless . Can you remove"I removed a single "This" that seems like the abandoned start of a sentence." from the commit?

**Comment by MaxKless** [comment]
> 
> 
> Thanks @MaxKless . Can you remove "I removed a single "This" that seems like the abandoned start of a sentence." from the commit?

Done :)

**Comment by MaxKless** [comment]
Should I close this PR?

**Comment by newhoggy** [comment]
Fixed in https://github.com/input-output-hk/cardano-node/pull/2860.

Thanks!

**Pull request closed without merging**
