### PR TITLE
Script ToJSON instances serialises the full script

### PR DESCRIPTION
**Pull request by ch1bo**
Mirrored changes of https://github.com/input-output-hk/cardano-node/pull/4138 on origin `cardano-node` repository and targeting `master` per request of @Jimbo4350

### CODE REVIEW

**Review by dcoutts — APPROVED** [review]
Looks plausible to me.

**Comment by ch1bo** [comment]
Thanks. The build error on Windows seems unrelated? How can we get this merged now?

**Review by Jimbo4350 — APPROVED** [review]
LGTM. Can you squash the commits?

**Pull request merged**
