### PR TITLE
Add LedgerStateBabbage patter synonym

### PR DESCRIPTION
**Pull request by eyeinsky**
(Couldn't test the change because when running `cabal build cardano-node` I get:
```
unknown package: cardano-binary (dependency of byron-spec-ledger)
```

`cardano-binary` appears to be a package in the `cardano-base` repository, which is not linked from cardano-node's cabal.project -- is cardano-binary gotten through other means?)

### CODE REVIEW

**Comment by LudvikGalois** [comment]
> Couldn't test the change
You may need to run `cabal update` from within the repo itself so it can find packages that are hosted on https://input-output-hk.github.io/cardano-haskell-packages.

**Comment by eyeinsky** [comment]
Got it building and fixed remaining issues :)

**Comment by eyeinsky** [comment]
Got stuck adding these lines here:
https://github.com/input-output-hk/cardano-node/pull/4577/files#diff-d737539ff36d894d150936c9ded4e3b9137053c90242225356549b60e17626ccR281-R282

Error:
```
StakeCredentialHistory.hs:282:100: error:
    • Could not deduce (HasField
                          "_protocolVersion"
                          (cardano-ledger-babbage-0.1.0.0:Cardano.Ledger.Babbage.PParams.PParams
                             (cardano-ledger-babbage-0.1.0.0:Cardano.Ledger.Babbage.BabbageEra
                                StandardCrypto))
                          L.ProtVer)
        arising from a use of ‘getPV’
      from the context: IsCardanoEra era
        bound by a pattern with constructor:
                   BlockInMode :: forall era mode.
                                  IsCardanoEra era =>
                                  Block era -> EraInMode era mode -> BlockInMode mode,
                 in a lambda abstraction
        at StakeCredentialHistory.hs:(257,13)-(259,17)
    • In the expression: getPV ls
      In the first argument of ‘Just’, namely
        ‘(L.nesRu ls, getGoSnapshot ls, getBalances ls, getPV ls)’
      In the expression:
        Just (L.nesRu ls, getGoSnapshot ls, getBalances ls, getPV ls)
    |
282 |                        ("babbage", L.nesEL ls, Just (L.nesRu ls, getGoSnapshot ls, getBalances ls, getPV ls))
    |                                                                                                    ^^^^^^^^

```

**Comment by eyeinsky** [comment]
Converted this to draft, should have been from the beginning.

**Comment by newhoggy** [comment]
To be merged in https://github.com/input-output-hk/cardano-node/pull/5001

**Comment by newhoggy** [comment]
Thanks for the contribution!

**Pull request closed without merging**
