### PR TITLE
CAD-4727 Change the default UTxO HD backend to `InMemory`.

### PR DESCRIPTION
**Pull request by jorisdral**
```bash
$ cabal run exe:cardano-node -- run
Up to date
Node configuration: NodeConfiguration {... , ncLedgerDBBackend = InMemory, ...}
# ...
```

### CODE REVIEW

**Review by dnadales — COMMENTED** [review]
Thanks. We need to update the documentation as well, explaining what the default is.

**Comment by Jimbo4350** [comment]
@jorisdral in the node we _strongly_ discourage long running feature branches. Can you merge what you have and commit to master to avoid an inevitable massive diff? cc: @dnadales

**Comment by Jimbo4350** [comment]
@jorisdral in the node we _strongly_ discourage long running feature branches. Can you merge what you have and continue to commit to master to avoid an inevitable massive diff? cc: @dnadales

**Comment by dnadales** [comment]
Hi Jordan. This pr pertains to the utxo HD feature branch. Sorry about the
confusion. We cannot merge that yet, and when we do well make sure we'll
make it in manageable increments.

**Review by dnadales — APPROVED** [review]

**Pull request merged**
