### PR TITLE
tx-generator: Fix multi-threaded use of tx-streams.

### PR DESCRIPTION
**Pull request by MarcFontaine**
* Put the tx-streams behind an `MVar`.
* Replace 'BechmarkTx' with generic 'NtoM'.
* Remove 'RunBenchmarkAux' and cleanups.
* Remove global state for 'TFee' and 'TTxAdditionalSize'

### CODE REVIEW

**Comment by MarcFontaine** [comment]
This PR addresses https://github.com/input-output-hk/cardano-node/issues/4428.

**Comment by MarcFontaine** [comment]
Todo: Fix 'Selftest.testscript'

**Review by mgmeier — APPROVED** [review]

**Review by deepfire — APPROVED** [review]

**Pull request merged**
