### PR TITLE
Sync percentage fixed.

### PR DESCRIPTION
**Pull request by denisshevchenko**
Sync progress (as a part of `NodeState` datapoint) for `cardano-tracer` is fixed now.

### CODE REVIEW

**Review by jutaro — CHANGES_REQUESTED** [review]
Why not: syncProgressPct :: SyncPercentage?

**Comment by denisshevchenko** [comment]
@jutaro Thanks, fixed.

**Review by jutaro — APPROVED** [review]

**Review by deepfire — APPROVED** [review]
bors r+

**Review by deepfire — APPROVED** [review]
bors r+

**Pull request merged**
