### PR TITLE
Tx gen: real TPS and node network parameters

### PR DESCRIPTION
**Pull request by denisshevchenko**
Now tx generator doesn't contain hardcoded values of TPS and target node's host and port.

### CODE REVIEW

**Comment by denisshevchenko** [comment]
@deepfire @Jimbo4350 Script `./scripts/shelley-testnet.sh` doesn't work again:

1. Invalid argument `node` (we don't need anymore?).
2. Invalid argument `-n` (now accepts only full form `--node-id`).

Moreover:

```
cardano-node: handleSimpleNode: own address NodeAddress {naHostAddress = ::1, naPort = 3000} not found in topology                                                                             
CallStack (from HasCallStack):                                                                  
  error, called at src/Cardano/Node/Run.hs:157:22 in cardano-node-3.0.1.87-inplace:Cardano.Node.Run
```

**Comment by deepfire** [comment]
@denisshevchenko, the script fixes are in https://github.com/input-output-hk/cardano-node/pull/207

**Pull request merged**
