### PR TITLE
fix IPv4/v6 use message

### PR DESCRIPTION
**Pull request by gufmar**
minor message fix, to prevent mistakes when users consider the "failed to parse IPvX" console error message

### CODE REVIEW

**Review by karknu — COMMENTED** [review]
LGTM.

**Comment by nc6** [comment]
I think this goes against the point of the message, which is to refer the user to the IPv6 syntax if they accidentally use the IPv4 one and vice verse

**Comment by gufmar** [comment]
I see. from this point of view it makes sense. 
If one has a typo/mistake in the address, without using the wrong ip-type the message is a bit misleading. 
May say: "_If you want to use an IPv4 address, please use ..._" ?

**Comment by Jimbo4350** [comment]
@gufmar 
>I think this goes against the point of the message, which is to refer the user to the IPv6 syntax if they accidentally use the IPv4 one and vice verse
I believe this was the original intention @cblp

**Comment by cblp** [comment]
Yes, the current message suggests _another_ option. Sorry, I'm not a native English speaker, if somebody knows how to express this intention better please write it.

**Review by cblp — CHANGES_REQUESTED** [review]
No need to double help. It's needed to guide the user.

**Comment by gufmar** [comment]
sorry wrong click (re-opened)
I would suggest expressing if the value for the used option is wrong, that this value is not valid for this option:
_This is not a valid IPv4 address_
Then if one by mistake has used an IPv6 address he should understand that this option is not for this address type and he must look for the right option.

**Comment by cblp** [comment]
Good idea! Please write the code.

**Comment by newhoggy** [comment]
Related PR https://github.com/input-output-hk/cardano-node/pull/2691

**Comment by cblp** [comment]
@gufmar please evaluate the new wording

**Comment by gufmar** [comment]
Sorry, I missed this (in-between so many cardano-node notifications)
looks good to me

**Pull request closed without merging**
