### PR TITLE
Separate shutdown-ipc and shutdown-on-slot-synced

### PR DESCRIPTION
**Pull request by Jimbo4350**
Currently these two features are intertwined when they should be treated as separate things.

### CODE REVIEW

**Comment by rvl** [comment]
Hi @Jimbo4350, please refer to PR input-output-hk/cardano-launcher#130 for test results.

**Review by MarcFontaine — APPROVED** [review]
LGTM

**Review by newhoggy — APPROVED** [review]

**Comment by Jimbo4350** [comment]
bors merge

**Pull request merged**
