### PR TITLE
Add Plutus example that computes sum [1..n]

### PR DESCRIPTION
**Pull request by MarcFontaine**
The benchmarking team uses this plutus script to test smart contracts with changing running times.

### CODE REVIEW

**Review by erikd — COMMENTED** [review]
Why is there a `plutus-example` directory inside a `plutus-example` directory? Sure on of them is redundant.

**Comment by MarcFontaine** [comment]
> Why is there a `plutus-example` directory inside a `plutus-example` directory? Sure one of them is redundant.

Building the Plutus examples is more tricky than it seems.
(Circular dependencies, pinning dependencies to the right versions etc).
That is also why the Plutus examples have their own `cabal.project` file.
I do not know all the details, I'm just building on existing work by Jordan.

**Review by Jimbo4350 — APPROVED** [review]
:+1:

**Pull request merged**
