### PR TITLE
Update to the latest version ouroboros-network

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by mrBliss** [comment]
btw, master has already changed and is (at the time of writing this commit) https://github.com/input-output-hk/ouroboros-network/commit/723d0ae621bfbc5b95b5813820badf90da22340f

**Comment by coot** [comment]
@mrBliss ok I'll update the PR, there seems to be no breaking changes.

**Comment by coot** [comment]
@mrBliss done

**Comment by nc6** [comment]
Closing in favour of #138, which also bumps various other dependencies at the same time.

**Pull request closed without merging**
