### PR TITLE
Update cli to allow Alonzo era queries

### PR DESCRIPTION
**Pull request by Jimbo4350**

### CODE REVIEW

**Comment by dcoutts** [comment]
Good stuff. I've cherry-picked most (or possibly all) of the changes from the first two commits here into #2759 and in the process I've reviewed, tweaked and extended them.

So I suggest rebasing on #2759 or master once that's merged.

**Comment by dcoutts** [comment]
Rebased on master.

**Comment by Jimbo4350** [comment]
LGTM!

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by dcoutts** [comment]
bors merge

**Pull request merged**
