### PR TITLE
Add Missing Documentation and Cabal Flags

### PR DESCRIPTION
**Pull request by JamesRobertKelley**
Issue
-----------
- Wrote better build instructions to replace missing instructions.

- Noticed there were some missing Cabal flags, so I added them.

- Enhanced the style guide.

Checklist
---------
- [x] This PR contains all the work required to resolve the linked issue.

- [x] The work contained has sufficient documentation to describe what it does and how to do it.

- [x] The work has sufficient tests and/or testing.

- [x] I have committed clear and descriptive commits. Be considerate as somebody else will have to read these.

- [ ] I have added the appropriate labels to this PR.

### CODE REVIEW

**Comment by mark-stopka** [comment]
As this is clearly a work derived from #597 and #640, you could just as well submit a `git revert -m 1 df71c429494bb0aa330f720250bc5a12b2579a48`.

**Comment by JamesRobertKelley** [comment]
> As this is clearly a work derived from #597 and #640, you could just as well submit a `git revert -m 1 df71c429494bb0aa330f720250bc5a12b2579a48`.

You should compare the two sets of instructions side-by-side. You will find the new instructions contain my own wording, are direct in content, use clearer formatting, and better follows the IOHK conventions.

Most importantly, I will not request the instructions to be removed at any point in the future.

**Comment by mark-stopka** [comment]
> You should compare the two sets of instructions side-by-side. You will find the new instructions contain my own wording, are direct in content, use clearer formatting, and better follows the IOHK conventions.

By which you just effectively described the legal definition of derived work, thank you for validating the argument made.

> Most importantly, I will not request the instructions to be removed at any point in the future.

I see no reason why that should hold any merit in a copyright infringement civil litigation under the [common legal procedures](https://en.wikipedia.org/wiki/Civil_law_(legal_system)), but I am certainly not qualified to comment of it's applicability under the [Common law practices](https://en.wikipedia.org/wiki/Common_law) common for civil litigation in the US.

**Comment by JamesRobertKelley** [comment]
> > You should compare the two sets of instructions side-by-side. You will find the new instructions contain my own wording, are direct in content, use clearer formatting, and better follows the IOHK conventions.
> 
> By which you just effectively described the legal definition of derived work, thank you for validating the argument made.
> 
> > Most importantly, I will not request the instructions to be removed at any point in the future.
> 
> I see no reason why that should hold any merit in a copyright infringement civil litigation under the [common legal procedures](https://en.wikipedia.org/wiki/Civil_law_(legal_system)), but I am certainly not qualified to comment of it's applicability under the [Common law practices](https://en.wikipedia.org/wiki/Common_law) common for civil litigation in the US.

Just in case you are curious:
- What I wrote is well within US legal guidelines for copyright. I am very familiar with US copyright law.
- You don't own the process of installing cardano-node, so following that process with my documentation is legit no matter how you look at it.
- This is an open-source project. You don't have any copyright claims in the first place.

**Comment by mark-stopka** [comment]
> This is an open-source project. You don't have any copyright claims in the first place.

If you say so, I'd start with [Section 2 onward](https://opensource.guide/legal/).

**Comment by JamesRobertKelley** [comment]
> > This is an open-source project. You don't have any copyright claims in the first place.
> 
> If you say so, I'd start with [Section 2 onward](https://opensource.guide/legal/).

My work is legal and protected from any of your claims. Even in the most strict regime, my work different than your work. I won't respond to any more of your toxic messages.

**Comment by mark-stopka** [comment]
> I won't respond to any more of your toxic messages.

Nobody was forcing you to reply to even a single one. Word toxic is getting popular I see.

**Pull request closed without merging**
