### PR TITLE
Update Cardano.Api.Script in preparation for the Alonzo era

### PR DESCRIPTION
**Pull request by Jimbo4350**

### CODE REVIEW

**Comment by johnalotoski** [comment]
Adding a `hydra-dont-build` label to this PR as it's continually failing eval in hydra, but consuming memory each time it tries.  Please feel free to remove the label when you need to continue work on this.

**Comment by Jimbo4350** [comment]
> Adding a `hydra-dont-build` label to this PR as it's continually failing eval in hydra, but consuming memory each time it tries. Please feel free to remove the label when you need to continue work on this.

Thanks @johnalotoski !

**Comment by dcoutts** [comment]
Rebased on top of #2657 and significantly extended.

**Review by dcoutts — APPROVED** [review]
:tada:

**Comment by dcoutts** [comment]
bors merge

**Pull request merged**
