### PR TITLE
Trace full `SelectView` when changing chain (including tiebreaker VRF)

### PR DESCRIPTION
**Pull request by amesgen**
# Description

Demo for integrating https://github.com/input-output-hk/ouroboros-consensus/pull/384 (and https://github.com/input-output-hk/ouroboros-consensus/pull/398) into the next node release (8.6).

These commits can be cherry-picked onto the 8.6 integration branch.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
  - integration tests
  See [Runnings tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

### CODE REVIEW

**Comment by teodanciu** [comment]
Sorry, wanted to update from master and  forgot to select "Rebase" instead of "Merge", so force-pushed again with the previous version before the update  ( 741862b ) .

**Comment by teodanciu** [comment]
Rebased on master,  in order to integrate it for 8.6

**Comment by amesgen** [comment]
> EDIT: After reading the description about cherry-picking the commits on the release branch, I now have doubts whether this should have been rebased, sorry.
> I can change it back to the commit before the rebase ( [741862b](https://github.com/input-output-hk/cardano-node/commit/741862bb06cce240a77bc605b344795ec50b2275) ) , if you can let me know @amesgen .

No problem, cherry-picking was just one possible option, feel free to rebase this branch or cherry-pick the commits on a dedicated one, whatever is more convenient for you!

**Comment by amesgen** [comment]
Has been integrated in #5516

**Pull request closed without merging**
