### PR TITLE
Api script eras

### PR DESCRIPTION
**Pull request by dcoutts**
This brings it most of Jordan's PR #2010 but:
 * rebased for the recent module splitting
 * step by step, in several small commits
 * in various places we are able to make things shorter and more things be parametrised by era (rather than separate per era)
 * renames 'MultiSigScript' language to 'SimpleScript'
 * adds a 'SimpleScript' pattern for the Script type
 * does not include the tests for the extra eras (these will need rebasing)
 * does not include the WIP parts to actually use the new ledger libs for the conversion

### CODE REVIEW

**Review by Jimbo4350 — APPROVED** [review]
LGTM!

**Review by intricate — APPROVED** [review]

**Comment by dcoutts** [comment]
bors merge

**Comment by dcoutts** [comment]
bors merge

**Comment by dcoutts** [comment]
Rebased on master to pick up the chairman fixes from #2078. :crossed_fingers:

**Comment by dcoutts** [comment]
bors merge

**Pull request merged**
